---
permalink: windows/concept_prerequisites_for_performing_rolling_upgrade.html 
sidebar: sidebar 
keywords: perform, roll, upgrade, prerequisite, environment, certain, requirement 
summary: Vor der Durchführung des Rolling Upgrades müssen Sie sicherstellen, dass Ihre Umgebung bestimmte Anforderungen erfüllt. 
---
= Voraussetzungen für das Durchführen eines Rolling Upgrades
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Durchführung des Rolling Upgrades müssen Sie sicherstellen, dass Ihre Umgebung bestimmte Anforderungen erfüllt.

* Wenn Sie eine ältere Version als SnapManager 3.1 verwenden und ein Rolling Upgrade auf SnapManager 3.3 oder höher durchführen möchten, müssen Sie zuerst auf 3.2 und dann auf die neueste Version aktualisieren.
+
Sie können direkt von SnapManager 3.2 auf SnapManager 3.3 oder höher aktualisieren.

* Externe Skripte, die zur Durchführung externer Datensicherung oder Datenaufbewahrung verwendet werden, müssen gesichert werden.
* Die SnapManager-Version, auf die Sie aktualisieren möchten, muss installiert sein.
+

NOTE: Wenn Sie ein Upgrade von einer älteren Version als SnapManager 3.1 auf SnapManager 3.3 oder höher durchführen, müssen Sie zuerst SnapManager 3.2 installieren und ein Rolling Upgrade durchführen. Nach dem Upgrade auf 3.2 können Sie SnapManager 3.3 oder höher installieren und ein weiteres Rolling Upgrade auf SnapManager 3.3 oder höher durchführen.

* Die SnapDrive für Windows-Version, die von der SnapManager-Version unterstützt wird, auf die Sie aktualisieren möchten, muss installiert sein.
+
Informationen zum Installieren von SnapDrive finden Sie unter SnapDrive-Dokumentationssatz.

* Die Repository-Datenbank muss gesichert werden.
* Die SnapManager Repository-Auslastung sollte mindestens betragen.
* Wenn der zu aktualisierenden Host ein Repository verwendet, dürfen SnapManager-Vorgänge nicht auf den anderen Hosts ausgeführt werden, die dasselbe Repository verwenden.
+
Die Vorgänge, die auf den anderen Hosts geplant oder ausgeführt werden, warten darauf, bis das Rolling Upgrade abgeschlossen ist.

* Profile, die auf dieselbe Repository-Datenbank verweisen, müssen mit unterschiedlichen Namen in den SnapManager-Server-Hosts erstellt werden.
+
Wenn Sie Profile mit dem gleichen Namen verwenden, schlägt das Rolling Upgrade der Repository-Datenbank ohne Warnung fehl.

* SnapManager-Vorgänge dürfen nicht auf dem Host ausgeführt werden, der gerade aktualisiert wird.



NOTE: Das Rolling Upgrade wird länger ausgeführt, wenn die Anzahl der Backups der Hosts, die zusammen aktualisiert werden, steigt. Die Dauer des Upgrades kann je nach Anzahl der Profile und Backups variieren, die mit einem bestimmten Host verbunden sind.

*Verwandte Informationen*

xref:task_installing_snapmanager_for_oracle.adoc[Installation von SnapManager für Oracle]

http://mysupport.netapp.com/["Dokumentation auf der NetApp Support Site: mysupport.netapp.com"]
