---
permalink: windows/concept_protecting_database_backups_by_using_post_scripts.html 
sidebar: sidebar 
keywords: enable, protect, database, backup, postscript, snapmirror, snapvault, relationship, postscript, cli, gui 
summary: SnapManager ermöglicht Ihnen, Datenbank-Backups mithilfe von Postskripten zu schützen, wenn eine SnapMirror oder SnapVault Beziehung zwischen den primären und sekundären Storage-Systemen hergestellt wird. Es können Standard-Postskripte für die Nachbearbeitung des Backup-Vorgangs über die SnapManager CLI und GUI verwendet werden. 
---
= Sicherung von Datenbank-Backups mithilfe von Postskripten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager ermöglicht Ihnen, Datenbank-Backups mithilfe von Postskripten zu schützen, wenn eine SnapMirror oder SnapVault Beziehung zwischen den primären und sekundären Storage-Systemen hergestellt wird. Es können Standard-Postskripte für die Nachbearbeitung des Backup-Vorgangs über die SnapManager CLI und GUI verwendet werden.

Folgende Standard-Postscripts sind unter default_install_Directory\Plugins\Backup\create\post verfügbar:

* Das SnapMirror Postscript, Mirror_the_Backup.cmd wenn sie Data ONTAP in 7-Mode verwenden
* Das SnapVault Postscript Vault_the_Backup.cmd, wenn Sie Data ONTAP in 7-Mode verwenden
* Das SnapMirror Postscript, Mirror_the_Backup_cDOT.cmd wenn sie Clustered Data ONTAP verwenden
* Das SnapVault Postscript Vault_the_Backup_cDOT.cmd wenn sie Clustered Data ONTAP verwenden


Weitere Informationen finden Sie in der Version readme.txt unter default_install_Directory\Plugins.

SnapManager 3.1 oder eine frühere Version bietet Vorverarbeitung- oder Nachbearbeitungsskripten nur für Klonvorgänge. SnapManager 3.2 oder höher bietet Vorverarbeitungs- und Nachbearbeitungsskripte für Backup- und Restore-Vorgänge. Diese Skripte können vor oder nach den Backup- oder Wiederherstellungsvorgängen ausgeführt werden.


NOTE: Die Skripte werden nur als Referenz bereitgestellt. Sie wurden mit SnapDrive 7.0 für Windows oder höher oder höher getestet, funktionieren aber möglicherweise nicht in allen Umgebungen. Sie sollten die Skripte auf der Grundlage Ihrer Anforderungen für den sekundären Schutz anpassen. Die Skripte funktionieren nicht mit SnapDrive Versionen vor 6.2.
