---
permalink: windows/concept_cloning_methods.html 
sidebar: sidebar 
keywords: clone, cloning, method, database 
summary: Sie können eine Datenbank mit einer von zwei Methoden klonen. Die von Ihnen gewählte Methode wirkt sich auf den Erstellungsvorgang des Klons aus. 
---
= Klonmethoden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Datenbank mit einer von zwei Methoden klonen. Die von Ihnen gewählte Methode wirkt sich auf den Erstellungsvorgang des Klons aus.

In der folgenden Tabelle werden die Klonmethoden und ihre Auswirkung auf den Vorgang zum Erstellen von Klonen und seine Option -Reserve beschrieben. Eine LUN kann mit beiden Methoden geklont werden.

|===
| Klonmethode 


| Beschreibung 


| Clone create -Reserve 


 a| 
Klonen von LUNs



 a| 
Es wird eine neue Klon-LUN innerhalb desselben Volumes erstellt.



 a| 
Wenn -Reserve für eine LUN auf „yes“ eingestellt ist, ist der Speicherplatz für die volle LUN-Größe innerhalb des Volume reserviert.



 a| 
Klonen von Volumes



 a| 
Es wird ein neuer FlexClone erstellt und die Klon-LUN innerhalb des neuen Klon-Volume vorhanden ist. Verwendet FlexClone Technologie.



 a| 
Wenn -Reserve für ein Volume auf „ja“ eingestellt ist, ist der Speicherplatz für die volle Volume-Größe innerhalb des Aggregats reserviert.

|===