---
permalink: windows/concept_accessing_snapmanager.html 
sidebar: sidebar 
keywords: command-line, interface, cli, graphical, user, gui, accessing 
summary: 'Der Zugriff auf SnapManager erfolgt entweder über die Befehlszeilenschnittstelle (CLI) oder über die grafische Benutzeroberfläche (GUI).' 
---
= Zugriff auf SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Zugriff auf SnapManager erfolgt entweder über die Befehlszeilenschnittstelle (CLI) oder über die grafische Benutzeroberfläche (GUI).

Sie haben folgende Möglichkeiten, verschiedene SnapManager-Vorgänge auszuführen:

* Durch Eingabe von Befehlen in der CLI auf einem Host, der sich im gleichen Netzwerk wie der Datenbank-Host befindet.
+
Eine Liste aller Befehle und eine Erläuterung ihrer Optionen und Argumente finden Sie im Kapitel Command Reference.

+
Um auf die CLI zuzugreifen, klicken Sie *Start* > *Alle Programme* > *NetApp* > *SnapManager für Oracle* > *Starten Sie die SMO Befehlszeilenschnittstelle (CLI)*.

* Durch Zugriff auf die GUI auf einem Host in demselben Netzwerk wie der Datenbank-Host.
+
Die GUI bietet einfache und benutzerfreundliche Assistenten, mit denen Sie verschiedene Aufgaben ausführen können.



*Verwandte Informationen*

xref:concept_snapmanager_for_oraclefor_sap_command_reference.adoc[Befehlsreferenz für SnapManager für Oracle]
