---
permalink: windows/concept_snapmanager_security.html 
sidebar: sidebar 
keywords: perform, operation, appropriate, credential, security, authentication 
summary: Sie können SnapManager Vorgänge nur ausführen, wenn Sie die entsprechenden Anmeldedaten besitzen. Die Sicherheit in SnapManager unterliegt der Benutzerauthentifizierung. 
---
= Wie SnapManager die Sicherheit gewährleistet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapManager Vorgänge nur ausführen, wenn Sie die entsprechenden Anmeldedaten besitzen. Die Sicherheit in SnapManager unterliegt der Benutzerauthentifizierung.

SnapManager gewährleistet die Sicherheit, indem die Benutzerauthentifizierung über Passworteinforderungen oder durch Festlegen von Benutzeranmeldeinformationen angefordert wird. Ein effektiver Benutzer wird beim SnapManager-Server authentifiziert und autorisiert.

Die SnapManager Anmeldedaten und die Benutzerauthentifizierung unterscheiden sich erheblich von SnapManager 3.0:

* In SnapManager-Versionen vor 3.0 würden Sie bei der Installation von SnapManager ein willkürliches Serverkennwort festlegen. Wer den SnapManager-Server nutzen möchte, braucht das SnapManager-Server-Passwort. Das SnapManager-Server-Passwort muss den Benutzeranmeldeinformationen mit dem smo-Befehl „set-serm“ hinzugefügt werden.
* In SnapManager (3.0 und höher) wurde das SnapManager-Serverpasswort durch die Authentifizierung des individuellen Betriebssystems (OS) ersetzt. Wenn Sie den Client nicht vom selben Server wie den Host ausführen, führt der SnapManager-Server die Authentifizierung durch, indem Sie die Benutzernamen und Passwörter des Betriebssystems verwenden. Wenn Sie nicht zur Eingabe Ihrer OS-Passwörter aufgefordert werden möchten, können Sie die Daten unter Verwendung des Befehls smo cridential set -Host im SnapManager-Benutzeranmeldungs-Cache speichern.
+

NOTE: Der Befehl smo Anmeldeinformation set -Host speichert Ihre Anmeldeinformationen, wenn die Eigenschaft Host.anmeldungs.persist in der Datei smo.config auf true gesetzt ist.



*Beispiel*

Benutzer1 und User2 teilen sich ein Profil namens Prof2. User2 kann eine Sicherung von „database1“ in Host1 nicht ohne die Berechtigung zum Zugriff auf Host1 durchführen. User1 kann eine Datenbank nicht ohne Berechtigung zum Zugriff auf host3 klonen.

In der folgenden Tabelle werden die verschiedenen Berechtigungen beschrieben, die den Benutzern zugewiesen sind:

|===


| Berechtigungstyp | Benutzer1 | Benutzer2 


 a| 
Host-Passwort
 a| 
Host1, Host2
 a| 
Host2, Host3



 a| 
Repository-Kennwort
 a| 
Repos. 1
 a| 
Repos. 1



 a| 
Profilkennwort
 a| 
Prof1, Prof2
 a| 
Prof2

|===
Wenn User1 und User2 keine freigegebenen Profile haben, nimmt an, dass User1 Berechtigungen für die Hosts mit Namen Host1 und Host2 hat, und User2 hat Berechtigungen für den Host namens Host2. User2 kann nicht einmal die nicht-profilbefehlen wie dump und System verify auf Host1 ausführen.
