---
permalink: windows/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: Markeninformationen 
---
= Markeninformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ, AltaVault, Arch Design, ASUP, AutoSupport, Campaign Express, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Element, Fitness, Flash Accel, Flash Cache, Flash Pool, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, Fueled by SolidFire, GetSuccessful, Helix Design, LockVault, Manage ONTAP, MetroCluster, MultiStore, NetApp, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANscreen, SANshare, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore Snapshot, SnapValidator, SnapVault, SolidFire, SolidFire Helix, StorageGRID, SyncMirror, Tech OnTap, Unbound Cloud und WAFL sowie weitere Namen sind Marken oder eingetragene Marken von NetApp, Inc. in den Vereinigten Staaten und/oder anderen Ländern. Alle anderen Marken oder Produkte sind Warenzeichen oder eingetragene Warenzeichen ihrer jeweiligen Inhaber und sollten als solche behandelt werden. Eine aktuelle Liste der NetApp -Marken ist im Internet verfügbar.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
