---
permalink: windows/reference_the_smosmsapbackup_restore_command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, backup, smo 
summary: Sie können den Befehl Backup Restore ausführen, um Backups einer Datenbank oder eines Teils einer Datenbank wiederherzustellen, und optional die Datenbankinformationen wiederherstellen. 
---
= Der Smo Backup Restore Befehl
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Befehl Backup Restore ausführen, um Backups einer Datenbank oder eines Teils einer Datenbank wiederherzustellen, und optional die Datenbankinformationen wiederherstellen.



== Syntax

[listing]
----

        smo backup restore
-profile profile_name
\[-label label \| -id id\]
\[-files files \[files...\] \|
-tablespaces tablespaces \[tablespaces...\]\] \|
-complete \| -controlfiles\]
\[-recover \{-alllogs \| -nologs \| -until until\} \[-using-backup-controlfile\] \]
\[-restorespec restorespec \| \]\]
\[-preview\]

\[-recover-from-location path1 \[, path2\]\]
\[-taskspec taskspec\]
\[-dump\]
\[-force\]
\[-quiet \| -verbose\]
----


== Parameter

* *-profile Profile_Name*
+
Gibt die Datenbank an, die wiederhergestellt werden soll. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* * Name des Etiketts*
+
Stellt das Backup mit dem angegebenen Etikett wieder her.

* *-id-Guid*
+
Stellt die Sicherung mit der angegebenen GUID wieder her. Die GUID wird von SnapManager beim Erstellen eines Backups generiert. Sie können den Befehl smo Backup list verwenden, um die GUID für jedes Backup anzuzeigen.

* *Wählen Sie alle oder bestimmte Dateien*
+
Optional können Sie eine der folgenden Optionen verwenden:

+
** -Complete: Stellt alle Dateien in der Sicherung wieder her.
** -Tablespaceslist: Stellt nur die angegebenen Tablespaces aus dem Backup wieder her.
+
Sie müssen Leerzeichen verwenden, um die Namen in der Liste zu trennen.

** -Fileslist: Stellt nur die angegebenen Datendateien aus dem Backup wieder her.
+
Sie müssen Leerzeichen verwenden, um die Namen in der Liste zu trennen. Wenn die Datenbank ausgeführt wird, stellt SnapManager sicher, dass der Tablespace, der die Dateien enthält, offline ist.



* *-controlfiles*
+
Stellt die Kontrolldateien wieder her. SnapManager ermöglicht Ihnen, in einem einzigen Vorgang Kontrolldateien zusammen mit den Datendateien aus den Backups wiederherzustellen. Die Option -controlfiles ist unabhängig von anderen Parametern für den Wiederherstellungsumfang, wie z. B. -Complete, -Tablespaces und -Files.

* *-Erholung*
+
Stellt die Datenbank nach der Wiederherstellung wieder her. Sie müssen auch den Punkt angeben, an dem SnapManager die Datenbank wiederherstellen soll, indem Sie eine der folgenden Optionen verwenden:

+
** -Nologs: Stellt die Datenbank zum Zeitpunkt der Sicherung wieder her und wendet keine Logs an.
+
Sie können diesen Parameter für Online- oder Offline-Backups verwenden.

** -Alllogs: Stellt die Datenbank auf die letzte Transaktion oder Commit wieder her und wendet alle erforderlichen Protokolle an.
** -Bis Datum: Stellt die Datenbank bis zum angegebenen Datum und der angegebenen Zeit wieder her.
+
Sie müssen das Jahr-Monat-Datum verwenden: Stunde: Minute: Sekunde (yyyy-mm-dd:hh:mm:ss) Format. Verwenden Sie für Stunden je nach Datenbankeinstellung entweder das 12-Stunden- oder das 24-Stunden-Format.

** -Bis scn: Rollt die Datendateien weiter, bis sie die angegebene Systemändernummer (SCN) erreicht.
** -Using-Backup-controlfile: Stellt die Datenbank mit der Backup-Kontrolldatei wieder her.


* *-restaurespec*
+
Ermöglicht Ihnen, die Daten in einem aktiven File-System wiederherzustellen und aus den angegebenen Daten wiederherzustellen, indem Sie jede Original-Snapshot-Kopie einem aktiven File-System zuweisen. Falls Sie keine Option angeben, werden die Daten aus den Snapshot Kopien im primären Storage von SnapManager wiederhergestellt. Sie können eine der folgenden Optionen angeben:

+
** -Restorespec: Gibt die wiederherzustellenden Daten und das Wiederherstellungsformat an.


* * Vorschau*
+
Zeigt die folgenden Informationen an:

+
** Zur Wiederherstellung jeder Datei wird der Wiederherstellungsmechanismus (Wiederherstellung von Storage-seitigen Dateisystemen, Dateiwiederherstellung auf Storage-Seite oder Dateikopien auf Host-Seite) verwendet
** Warum effizientere Mechanismen nicht zur Wiederherstellung jeder Datei verwendet wurden, wenn Sie die Option -verbose angeben Wenn Sie die Option -Preview verwenden, müssen Sie Folgendes wissen:
** Die Option -Force hat keine Auswirkung auf den Befehl.
** Die Option -wiederherstellen hat keine Auswirkung auf den Befehl. Um eine Vorschau des Wiederherstellungsvorgangs anzuzeigen, muss die Datenbank gemountet werden. Wenn Sie eine Vorschau eines Wiederherstellungsplans anzeigen möchten und die Datenbank derzeit nicht angehängt ist, mountet SnapManager die Datenbank. Wenn die Datenbank nicht angehängt werden kann, schlägt der Befehl fehl, und SnapManager gibt die Datenbank in ihren ursprünglichen Status zurück.


+
Die Option -Preview zeigt bis zu 20 Dateien an. Sie können die maximale Anzahl von Dateien konfigurieren, die in der Datei smo.config angezeigt werden sollen.

* *-Recovery-from-location*
+
Gibt den externen Speicherort der Archivprotokolldateien an. SnapManager nimmt die Archivprotokolldateien vom externen Standort auf und verwendet diese für den Recovery-Prozess.

* *-taskSpec*
+
Gibt die XML-Datei für die Aufgabenspezifikation für die Vorverarbeitung oder Nachbearbeitung des Wiederherstellungsvorgangs an. Sie müssen den vollständigen Pfad der XML-Datei für die Aufgabenspezifikation angeben.

* *-dump*
+
Gibt an, die Speicherauszugsdateien nach dem Wiederherstellungsvorgang zu sammeln.

* *-Force*
+
Ändert ggf. den Datenbankstatus in einen niedrigeren Status als der aktuelle Status.

+
Standardmäßig kann SnapManager den Datenbankstatus während eines Vorgangs in einen höheren Status ändern. Diese Option ist nicht erforderlich, damit SnapManager die Datenbank in einen höheren Status ändert.

* *-ruhig*
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an. Sie können diese Option verwenden, um zu sehen, warum effizientere Wiederherstellungsprozesse nicht verwendet werden konnten, um die Datei wiederherzustellen.





== Beispiel

Im folgenden Beispiel wird eine Datenbank zusammen mit den Kontrolldateien wiederhergestellt:

[listing]
----
smo backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----
*Verwandte Informationen*

xref:concept_restoring_database_backup.adoc[Datenbank-Backups werden wiederhergestellt]

xref:task_restoring_backups_from_an_alternate_location.adoc[Wiederherstellen von Backups von einem alternativen Speicherort]

xref:task_creating_restore_specifications.adoc[Erstellen von Wiederherstellungsspezifikationen]
