---
permalink: windows/reference_the_smosmsapbackup_show_command.html 
sidebar: sidebar 
keywords: backup, show, command, display, information, protection, status 
summary: Mit dem Befehl Backup show können Sie detaillierte Informationen zu einem Backup anzeigen, einschließlich Sicherungsstatus, Backup-Aufbewahrungsklasse und Backups im primären und sekundären Speicher. 
---
= Der Befehl smo Backup show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Befehl Backup show können Sie detaillierte Informationen zu einem Backup anzeigen, einschließlich Sicherungsstatus, Backup-Aufbewahrungsklasse und Backups im primären und sekundären Speicher.



== Syntax

[listing]
----

        smo backup show
-profile profile_name
[-label label \[-data \| -archivelogs\] \| \[-id id\]
\[-quiet \| -verbose\]
----


== Parameter

* *-profile Profile_Name*
+
Gibt das Profil an, für das Backups angezeigt werden sollen. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* * Label*
+
Gibt die Bezeichnung des Backups an.

* *-Daten*
+
Gibt die Datendateien an.

* *-Archivprotokolle*
+
Gibt die Archivprotokolldateien an.

* *-id-id*
+
Gibt die Backup-ID an.

* *-ruhig*
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen der Konsole sowie Klon- und Verifizierungsdaten an.





== Beispiel

Im folgenden Beispiel werden ausführliche Informationen zum Backup angezeigt:

[listing]
----
smo backup show -profile SALES1 -label BTNFS -verbose
Backup id: 8abc013111a450480111a45066210001
Backup status: SUCCESS
Primary storage resources: EXISTS
Protection sate: NOT REQUESTED
Retention class: DAILY
Backup scope: FULL
Backup mode: OFFLINE
Mount status: NOT MOUNTED
Backup label: BTNFS
Backup comment:
RMAN Tag: SMO_BTNFS_1175283108815
Backup start time: 2007-03-30 15:26:30
Backup end time: 2007-03-30 15:34:13
Verification status: OK
Backup Retention Policy: NORMAL
Backup database: hsdb1
Checkpoint: 2700620
Tablespace: SYSAUX
Datafile: E:\disks\data\sysaux01.dbf [ONLINE]
...
Control Files:
File: E:\disks\data\control03.ctl
...
Archive Logs:
File: E:\disks\data\archive_logs\2_131_626174106.dbf
...
Host: Host1
File: E:\disks\data\hsdb\SMOBakCtl_1175283005231_0
...
Volume: hs_data
Snapshot: SMO_HSDBR_hsdb1_F_C_1_
8abc013111a450480111a45066210001_0
File: E:\disks\data\hsdb\SMOBakCtl_1175283005231_0
...
----
*Verwandte Informationen*

xref:task_viewing_backup_details.adoc[Anzeigen von Backup-Details]
