---
permalink: windows/reference_the_smosmsapbackup_create_command.html 
sidebar: sidebar 
keywords: run, backup, create, command, database, storage, system, smo 
summary: Sie können den Befehl Backup create ausführen, um Datenbank-Backups auf einem oder mehreren Speichersystemen zu erstellen. 
---
= Der Befehl smo Backup erstellen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Befehl Backup create ausführen, um Datenbank-Backups auf einem oder mehreren Speichersystemen zu erstellen.



== Syntax


NOTE: Bevor Sie diesen Befehl ausführen, müssen Sie ein Datenbankprofil mithilfe des Befehls Profile create erstellen erstellen.

[listing]
----

        smo backup create
-profile profile_name
{\[-full\{-auto \| -online \| -offline\}\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\]  |
\[-data \[\[-files files \[files\]\] \|
\[-tablespaces tablespaces \[tablespaces\]\] \[-label label\] \{-auto \| -online \| -offline\}
\[-retain \{-hourly \| -daily \| -weekly \| -monthly \| -unlimited\} \[-verify\] |
\[-archivelogs \[-label label\]\] \[-comment comment\]}

\[-backup-dest path1 \[ , path2\]\]
\[-exclude-dest path1 \[ , path2\]\]
\[-prunelogs \{-all \| -until-scn until-scn \| -until-date yyyy-MM-dd:HH:mm:ss\] \| -before \{-months \| -days \| -weeks \| -hours}}
-prune-dest prune_dest1,\[prune_dest2\]\]
\[-taskspec taskspec\]
\[-dump\]
-force
\[-quiet \| -verbose\]
----


== Parameter

* *-profile Profile_Name*
+
Gibt den Namen des Profils an, das mit der Datenbank verknüpft ist, die gesichert werden soll. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* *-Auto Option*
+
Wenn die Datenbank im Status „angehängt“ oder „Offline“ steht, führt SnapManager ein Offline-Backup durch. Wenn sich die Datenbank im offenen oder Online-Status befindet, führt SnapManager ein Online-Backup durch. Wenn Sie die Option -Force mit der Option -offline verwenden, erzwingt SnapManager ein Offline-Backup, selbst wenn die Datenbank derzeit online ist.

* *-Online-Option*
+
Gibt ein Online-Datenbank-Backup an.

+
** Wenn sich die lokale Instanz im Status beim Herunterfahren befindet und sich mindestens eine Instanz im offenen Status befindet, können Sie die Option -Force verwenden, um die lokale Instanz in den angehängten Status zu ändern.
** Wenn sich keine Instanz im Status „Open“ befindet, können Sie die Option „-Force“ verwenden, um die lokale Instanz in den Status „Open“ zu ändern.


* *-Offline-Option*
+
Gibt ein Offline-Backup an, während sich die Datenbank im Status Herunterfahren befindet. Wenn sich die Datenbank im offenen oder gemounteten Status befindet, schlägt das Backup fehl. Wenn die Option -Force verwendet wird, versucht SnapManager, den Datenbankstatus zu ändern, um die Datenbank für ein Offline-Backup herunterzufahren.

* *-Volloption*
+
Sicherung der gesamten Datenbank. Dazu gehören alle Daten, archivierte Log- und Kontrolldateien. Die archivierten Wiederherstellungsprotokolle und Kontrolldateien werden gesichert, unabhängig davon, welche Art von Backup Sie durchführen. Wenn Sie nur einen Teil der Datenbank sichern möchten, verwenden Sie die Option -files oder -Tablespaces.

* *-Datenoption*
+
Gibt die Datendateien an.

* *-Dateiliste*
+
Sichert nur die angegebenen Datendateien sowie die archivierten Protokoll- und Kontrolldateien. Trennen Sie die Liste der Dateinamen mit Leerzeichen. Wenn die Datenbank offen ist, überprüft SnapManager, ob sich die entsprechenden Tabellen im Online-Backup-Modus befinden.

* * -Tablespaces*
+
Sicherung nur der angegebenen Datenbanktablespaces plus der archivierten Protokoll- und Kontrolldateien Trennen Sie die Namen der Tablespaces durch Leerzeichen. Wenn die Datenbank offen ist, überprüft SnapManager, ob sich die entsprechenden Tabellen im Online-Backup-Modus befinden.

* * Label*
+
Gibt einen optionalen Namen für dieses Backup an. Dieser Name muss innerhalb des Profils eindeutig sein. Der Name kann Buchstaben, Zahlen, Unterstriche (_) und Bindestriche (-) enthalten. Es kann nicht mit einem Bindestrich beginnen. Wenn Sie keine Beschriftung angeben, erstellt SnapManager im Scope_type_date-Format eine Standardbeschriftung:

+
** Der Umfang ist entweder F, um ein vollständiges Backup anzuzeigen, oder P, um auf ein teilweises Backup hinzuweisen.
** Geben Sie C ein, um ein Offline-Backup (Cold) anzuzeigen, H für ein Online-Backup (Hot) oder Ein Für die automatische Sicherung, z. B. P_A_20081010060037IST, anzuzeigen.
** Datum ist Jahr, Monat, Tag und Uhrzeit des Backups.
+
SnapManager verwendet eine 24-Stunden-Zeit.



+
Beispiel: Wenn Sie am 16. Januar 2007 um 5:45:16 Uhr eine vollständige Sicherung mit offline der Datenbank durchgeführt haben Eastern Standard Time, SnapManager würde die Bezeichnung F_C_20070116174516EST erstellen.

* *-comment-Zeichenfolge*
+
Gibt einen optionalen Kommentar an, um dieses Backup zu beschreiben. Schließen Sie die Zeichenfolge in einzelne Anführungszeichen (').

+

NOTE: Einige Schalen entfernen die Anführungszeichen. In diesem Fall müssen Sie das Anführungszeichen mit einem umgekehrten Schrägstrich (\) angeben. Möglicherweise müssen Sie Folgendes eingeben: `\' this is a comment\'`.

* *-Verify Option*
+
Überprüft, ob die Dateien im Backup nicht beschädigt sind, indem Sie das Oracle dbv-Dienstprogramm ausführen.

+

NOTE: Wenn Sie die Option -verify angeben, wird der Backup-Vorgang erst abgeschlossen, wenn der Überprüfungvorgang abgeschlossen ist.

* *-Force Option*
+
Erzwingt eine Statusänderung, wenn sich die Datenbank nicht im richtigen Zustand befindet. Beispielsweise kann SnapManager den Status der Datenbank von Online- in Offline-Modus ändern, basierend auf dem von Ihnen angegebenen Backup-Typ und dem Status, in dem sich die Datenbank befindet.

+
** Wenn sich die lokale Instanz im Status beim Herunterfahren befindet und sich mindestens eine Instanz im offenen Status befindet, wird die lokale Instanz mit der Option -Force in den angehängten Status geändert.
** Wenn sich keine Instanz im Status Open befindet, wird die lokale Instanz mithilfe der Option -Force in den Status Open geändert.


* *-ruhig*
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an.

* *-halten Sie { - stündlich - jeden Tag -- monatlich - unbegrenzt}*
+
Gibt an, ob das Backup stündlich, täglich, wöchentlich, monatlich oder unbegrenzt aufbewahrt werden soll. Wenn die Option -Retention nicht angegeben ist, orientiert sich die Retention class standardmäßig an der Option -hourly. Mit der Option -unlimited können Sie Backups für immer aufbewahren. Die Option -unlimited macht das Backup nicht zur Löschung durch die Aufbewahrungsrichtlinie.

* *-Archivprotokolle-Option*
+
Erstellt Backup für Archivprotokolle

* *-Backup-dest path1, [, [path2]]*
+
Gibt die Ziele für das Archivprotokoll an, die für die Sicherung des Archivprotokolls gesichert werden sollen.

* *-exclude-dest path1, [, [path2]]*
+
Gibt die Ziele für das Archivprotokoll an, die vom Backup ausgeschlossen werden sollen.

* *-prunelogs {-all} -bis-scnbis-scn - bis-dateyyyyy-MM-dd:HH:mm:ss - vor {-Monaten
+
Löscht die Archivprotokolldateien aus den Zielen des Archivprotokolls basierend auf den bei der Erstellung eines Backups bereitgestellten Optionen. Die Option -all löscht alle Archivprotokolldateien aus den Archivprotokollzielen. Mit der Option -bis-scn werden die Archivprotokolldateien bis zu einer angegebenen Systemänderungsnummer (SCN) gelöscht. Mit der Option -bis-date werden die Archivprotokolldateien bis zum angegebenen Zeitraum gelöscht. Die Option -before löscht die Archivprotokolldateien vor dem angegebenen Zeitraum (Tage, Monate, Wochen, Stunden).

* *-prune-dest prune_dest1,prune_dest2*
+
Löscht die Archivprotokolldateien aus den Archivprotokollzielen, während die Sicherung erstellt wird.

* *-taskSpec taskSpec*
+
Gibt die XML-Datei für die Aufgabenspezifikation an, die für die Vorverarbeitung oder Nachverarbeitung des Backup-Vorgangs verwendet werden kann. Der vollständige Pfad der XML-Datei sollte zur Verfügung gestellt werden, während die Option -taskSpec angegeben wird.

* *-dump-Option*
+
Sammelt die Speicherauszugsdateien nach einem erfolgreichen oder fehlgeschlagenen Datenbanksicherungvorgang.





== Beispielbefehl

Mit dem folgenden Befehl wird ein vollständiges Online Backup erstellt, ein Backup auf dem Sekundärspeicher erstellt und die Aufbewahrungsrichtlinie auf einen täglichen Routineaufgaben setzt:

[listing]
----
smo backup create -profile SALES1 -full -online
-label full_backup_sales_May -profile SALESDB -force -retain -daily
Operation Id [8abc01ec0e79356d010e793581f70001] succeeded.
----
*Verwandte Informationen*

xref:task_creating_database_backups.adoc[Datenbank-Backups werden erstellt]

xref:reference_the_smosmsapprofile_create_command.adoc[Der Befehl smo profile create]
