---
permalink: windows/reference_the_smosmsap_clone_update_command.html 
sidebar: sidebar 
keywords: command, update, information, clone, comment, smo 
summary: Mit diesem Befehl werden Informationen zum Klon aktualisiert. Sie können den Kommentar aktualisieren. 
---
= Der Befehl smo Clone Update
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl werden Informationen zum Klon aktualisiert. Sie können den Kommentar aktualisieren.



== Syntax

[listing]
----

        smo clone update
-profile profile_name
\[-label label \| -id id\]
-comment  commment_text
\[-quiet \| -verbose\]
----


== Parameter

* *-profile Profile_Name*
+
Gibt den Namen des Profils an, das den zu aktualisierenden Klon enthält. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* *-id-id*
+
Gibt die ID für den Klon an. Die ID wird von SnapManager beim Erstellen eines Klons generiert. Verwenden Sie den Befehl smo Clone list, um die ID für jeden Klon anzuzeigen.

* * Label*
+
Gibt die Bezeichnung für den Klon an.

* *-Kommentar*
+
Zeigt den Kommentar an, der bei der Klonerstellung eingegeben wurde. Dies ist ein optionaler Parameter.

* *-ruhig*
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl

Im folgenden Beispiel wird der Klonkommentar aktualisiert.

[listing]
----
smo clone update -profile anson.pcrac5
-label clone_pcrac51_20080820141624EDT -comment See updated clone
----