---
permalink: windows/reference_the_smosmsap_operation_show_command.html 
sidebar: sidebar 
keywords: run, operation, show, command, list, summary, information, profile, smo, host 
summary: 'Sie können den Befehl „Operation show“ ausführen, um die Zusammenfassungsinformationen aller Vorgänge, die für das angegebene Profil durchgeführt wurden, aufzulisten. In der Ausgabe werden der Client-Benutzer \ (der Benutzer für den Client-PC\) und der effektive Benutzer (der Benutzer in SnapManager, der auf dem ausgewählten Host gültig ist) aufgelistet.' 
---
= Der Befehl smo Operation show
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Befehl „Operation show“ ausführen, um die Zusammenfassungsinformationen aller Vorgänge, die für das angegebene Profil durchgeführt wurden, aufzulisten. Die Ausgabe listet den Client-Benutzer (den Benutzer für den Client-PC) und den effektiven Benutzer (den Benutzer in SnapManager, der auf dem ausgewählten Host gültig ist) auf.



== Syntax

[listing]
----

        smo operation show
-profile profile_name
\[-label label \| -id id\]
\[-quiet \| -verbose\]
----


== Parameter

* *-profile Profile_Name*
+
Gibt den Namen des Profils an. Dieser Name kann bis zu 30 Zeichen lang sein und muss innerhalb des Hosts eindeutig sein.

* * Label*
+
Gibt die Bezeichnung für den Vorgang an.

* *-id-id*
+
Gibt die Kennung für den Vorgang an.

* *-ruhig*
+
Optional: Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Optional: Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an.





== Beispiel

In der folgenden Befehlszeile werden detaillierte Informationen über einen Vorgang angezeigt:

[listing]
----
# smo operation show -profile myprofile -id ff8080811295eb1c011295eb28230001
----
[listing]
----
Operation Attempted
   Operation ID: ff8080811295eb1c011295eb28230001
   Type:RestoreFor profile: myprofile
   With Force: No
   Performed on backup
   Operation ID: ff8080811295eb1c011296eb23290001
   Label: mylabel
Operation Runtime Information
   Status: SUCCESS
   Start date: 2007-07-16 13:24:09 IST
   End date: 2007-07-16 14:10:10 IST
   Client user: amorrow
   Effective user: amorrow
Host
   Host Run upon: Host3
   Process ID: 3122
   SnapManager version: 3.3
Repository
   Connection: user1@SMOREPO/hotspur:1521
   Repository version: 3.3
Resources in use
   Volume:
     ssys1:/vol/luke_ES0_0 (FlexClone)
   Filesystems:C:\\SnapManager_auto_mounts\\O-20120712052511170_0
----
*Verwandte Informationen*

xref:task_viewing_operation_details.adoc[Anzeigen von Betriebsdetails]
