---
permalink: windows/reference_the_smosmsapbackup_list_command.html 
sidebar: sidebar 
keywords: run, backup, list, command, display, information, profile, retention, protection, status, smo 
summary: Sie können den Befehl Backup list ausführen, um Informationen zu den Backups in einem Profil anzuzeigen, einschließlich Informationen zur Aufbewahrungsklasse und zum Sicherungsstatus. 
---
= Der Befehl smo Backup list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Befehl Backup list ausführen, um Informationen zu den Backups in einem Profil anzuzeigen, einschließlich Informationen zur Aufbewahrungsklasse und zum Sicherungsstatus.



== Syntax

[listing]
----

        smo backup list
-profile profile_name
-delimiter character
[-data | -archivelogs | -all]
\[-quiet \| -verbose\]
----


== Parameter

* *-profile Profile_Name*
+
Gibt das Profil an, für das Sie Backups auflisten möchten. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* *-Trennzeichen*
+
Zeigt jede Zeile in einer eigenen Zeile an. Die Attribute in der Zeile werden durch das angegebene Zeichen getrennt.

* *-Daten*
+
Gibt die Datendateien an.

* *-Archivprotokolle*
+
Gibt die Archivprotokolldateien an.

* *-ruhig*
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an. Schließen Sie die -verbose Option zum Anzeigen der Backup-IDs an.





== Beispiel

Im folgenden Beispiel werden die Backups für DAS SALES1-Profil aufgeführt:

[listing]
----
smo backup list -profile SALES1 -verbose
Start Date          Status  Scope  Mode    Primary  Label      Retention   Protection
------------------- ------- ------ ------- -------- -----      --------    ----------
2007-08-10 14:12:31 SUCCESS FULL   ONLINE  EXISTS   backup2    HOURLY      NOT REQUESTED
2007-08-05 12:08:37 SUCCESS FULL   ONLINE  EXISTS   backup4    UNLIMITED   NOT REQUESTED
2007-08-04 22:03:09 SUCCESS FULL   ONLINE  EXISTS   backup6    UNLIMITED   NOT REQUESTED
----
*Verwandte Informationen*

xref:task_viewing_a_list_of_backups.adoc[Anzeigen einer Liste von Backups]
