---
permalink: windows/task_customizing_e_mail_subject_for_a_new_profile.html 
sidebar: sidebar 
keywords: customize, email, subject, new, profile, create, customizing 
summary: Sie können den E-Mail-Betreff für das neue Profil anpassen, wenn Sie es erstellen. 
---
= Anpassen des E-Mail-Betreff für ein neues Profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den E-Mail-Betreff für das neue Profil anpassen, wenn Sie es erstellen.

Sie können den Betreff der E-Mail mithilfe des \{profile}_\{Operation-Name}_\{db-sid}_\{db-Host}_\{Startdatum}_\{Enddatum}_\{Status}-Musters anpassen oder Ihren eigenen Text eingeben.

|===


| Variablenname | Beschreibung | Beispielwert 


 a| 
Profil
 a| 
Profilname, der für den Datenbankvorgang verwendet wird
 a| 
PROF1



 a| 
Operation-Name
 a| 
Name des Datenbankvorgangs
 a| 
Backup, Daten-Backup, Daten- und Archivprotokolle Backup



 a| 
db-sid
 a| 
SID der Datenbank
 a| 
DB1



 a| 
db-Host
 a| 
Name des Hostservers
 a| 
Hosta



 a| 
Startdatum
 a| 
Startzeit der Datenbankoperation im Format mmdd:hh:ss yyyy
 a| 
April 27 21:00:45 PST 2012



 a| 
Enddatum
 a| 
Endzeit des Datenbankvorgangs im Format mmdd:hh:ss yyyy
 a| 
April 27 21:10:45 PST 2012



 a| 
Status
 a| 
Status des Datenbankvorgangs
 a| 
Erfolg

|===
Wenn Sie keinen Wert für die Variablen angeben, zeigt SnapManager die folgende Fehlermeldung an: Missing value(s) -subject.

. Geben Sie den folgenden Befehl ein: smo-Profil create -profileprofil [-profile-passwordprofile_password] -Repository-dbnamerepo_Service_Name-hostrepo_Host-portrepo_Port-Login-usernamerepo_username_addbnailgms2 [-{ protourly] { [-associence-adressem]} } [-associence [-ademnmnmninto] [-into] [-associmnmailmnmnmnmnmninto] [-into] [-into] [-into [-into] [-into] [-assailmnmaimnmaimninto] [-into] [-commnmaimnmailmnmnmnmnms2] [-adymnmnmnmnmninto] [-adym] [-adym] [-adymnmnmnmninto] [-ady

