---
permalink: windows/task_updating_target_database_hostname_associated_with_a_profile.html 
sidebar: sidebar 
keywords: snapmanager, oracle, ability, update, host, name, target, database, profile, updating, profile 
summary: 'SnapManager (3.2 oder höher) für Oracle bietet die Möglichkeit, den Hostnamen der Zieldatenbank im SnapManager-Profil zu aktualisieren.' 
---
= Der Host-Name der Zieldatenbank, der einem Profil zugeordnet ist, wird aktualisiert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager (3.2 oder höher) für Oracle bietet die Möglichkeit, den Hostnamen der Zieldatenbank im SnapManager-Profil zu aktualisieren.

* Das Home-Verzeichnis des lokalen Benutzers muss die Zuordnung zu den Profilen und Repositorys kennen.
* Die Sitzungen der SnapManager Graphical User Interface (GUI) müssen geschlossen werden.


Sie können das Profil mit dem neuen Hostnamen aktualisieren, indem Sie nur die CLI verwenden.

*Szenarien werden nicht unterstützt, wenn der Hostname der Zieldatenbank im Profil* geändert werden soll

Die folgenden Szenarien werden beim Ändern des Hostnamen der Zieldatenbank im Profil nicht unterstützt:

* Ändern des Host-Namens der Zieldatenbank mithilfe der SnapManager-GUI
* Rollback der Repository-Datenbank nach Aktualisierung des Host-Namens der Zieldatenbank des Profils durchführen
* Aktualisieren mehrerer Profile für einen neuen Hostnamen der Zieldatenbank durch Ausführen eines einzigen Befehls
* Ändern des Host-Namens der Zieldatenbank, wenn ein SnapManager-Vorgang ausgeführt wird



NOTE: Nachdem Sie den Hostnamen der Zieldatenbank im Profil aktualisiert haben, wird nur der Hostname der Zieldatenbank geändert. Alle anderen Konfigurationsparameter, die im Profil festgelegt sind, werden beibehalten.

Nachdem Sie den Hostnamen der Zieldatenbank aktualisiert haben, können Sie das Backup nicht löschen oder unmounten, wenn der Klon oder das bereitgestellte Backup nicht auf dem neuen Host verfügbar ist. In solchen Szenarien führen die Ausführung der SnapManager Vorgänge vom neuen Host zu Ausfällen sowie zu veralteten Einträgen im früheren Host. Um SnapManager-Vorgänge durchzuführen, müssen Sie zum früheren Hostnamen mithilfe der Profilaktualisierung zurücksetzen.

. Geben Sie folgenden Befehl ein: smo-Profil-Update -profileprofil [-profile-passwordprofile_password][-Database-dbnamedb_dbname-hostdb_Host [-siddb_sid] [-Login-usernamedb_username-adressnum{] [-{ commentail] [-{ commansion-comments2}}}] [-association-comments2] [-commented_adressem] [-commentary] [-commentation_adressem_adressum] [-commentary] [-commentermninct] [-commendbmninct] [-commendbmninct] [-ledbmninct] [-commendb] [-ledb] [-commendb] [-commendbmprompromations2] [-commendb] [-commendbmations2] [-commendb] [-commendb] [-commendbmprom
+
Weitere Optionen für diesen Befehl:

+
[-Force] [-noprompt]

+
|===


| Ihr Ziel ist | Dann... 


 a| 
*Ändern Sie den Hostnamen der Zieldatenbank*
 a| 
Geben Sie -hostNew_db_Host an

|===
. Geben Sie zum Anzeigen des Host-Namens der Zieldatenbank des Profils den folgenden Befehl ein: smo Profile show

