---
permalink: windows/task_order_of_performing_operations.html 
sidebar: sidebar 
keywords: snapmanager, enable, perform, operation, backup, cloning, clone, operation, order, perform 
summary: SnapManager ermöglicht Ihnen die Durchführung verschiedener Aufgaben, z. B. das Erstellen von Profilen, das Durchführen von Backups und das Klonen von Backups. Diese Vorgänge müssen in einer bestimmten Reihenfolge ausgeführt werden. 
---
= Reihenfolge der Durchführung von Vorgängen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager ermöglicht Ihnen die Durchführung verschiedener Aufgaben, z. B. das Erstellen von Profilen, das Durchführen von Backups und das Klonen von Backups. Diese Vorgänge müssen in einer bestimmten Reihenfolge ausgeführt werden.

. Erstellen Sie ein Profil in einem vorhandenen Repository mithilfe des Befehls smoprofile create.
+

NOTE: Der für die Zieldatenbank angegebene Oracle-Benutzer muss über sysdba-Berechtigungen verfügen.

+
Im folgenden Beispiel wird der Befehl zum Erstellen eines Profils gezeigt:

+
[listing]
----
smo profile create -profile prof1 -profile-password prof1cred
-repository -dbname HR1 -login -username admin -host server1 -port 1521
-database -dbname dedb -login -username db_oper2
-password dbpw1 -host server1 -port 1521
----
. Erstellen Sie ein Backup auf einem vorhandenen Profil mit dem smo Backup create Befehl.
+
Im folgenden Beispiel wird der Befehl zum Erstellen eines Backups gezeigt:

+
[listing]
----
smo backup create -profile prof1 -full -offline -label full_backup_prof1 -force
----
. Wiederherstellung eines Datenbank-Backups auf dem Primär-Storage mithilfe des smo Backup-Restore-Befehls
+
Das folgende Beispiel zeigt den Befehl zum Wiederherstellen eines Backups:

+
[listing]
----
smo backup restore -profile prof1 -label full_backup_prof1
-complete -recover -alllogs
----
. Erstellen Sie mit dem Befehl smo Clone template eine Klonspezifikation.
+
Sie können den Klon-Assistenten in der grafischen Benutzeroberfläche (GUI) verwenden, um eine Spezifikation für das Klonen einer Vorlage zu erstellen. Sie können die Klon-Spezifikationsdatei auch mit einem Texteditor erstellen.

. Klonen einer Datenbank mit einem vorhandenen Backup mit dem Befehl zum Erstellen von smo Clone.
+
Sie müssen über eine vorhandene Klonspezifikation verfügen oder eine Klonspezifikation erstellen, um die Storage- und Datenbank-Spezifikationen für den Klon anzugeben.

+
Im folgenden Beispiel wird der Befehl zum Erstellen eines Klons angezeigt:

+
[listing]
----
smo clone create -profile prof1 -backup-label full_backup_prof1
-newsid clone1 -label prof1_clone -clonespec C:\\clone_spec\\prof1_clonespec.xml
----

