---
permalink: unix-administration/concept_understanding_enabling_or_disabling_of_data_protection_in_profile.html 
sidebar: sidebar 
keywords: enable, disable, data, protection, creating, updating, database, profile, understand 
summary: Sie können den Datenschutz beim Erstellen oder Aktualisieren eines Datenbankprofils aktivieren oder deaktivieren. 
---
= Allgemeines zum Aktivieren oder Deaktivieren von Datenschutz in Profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Datenschutz beim Erstellen oder Aktualisieren eines Datenbankprofils aktivieren oder deaktivieren.

Um ein geschütztes Backup einer Datenbank auf den sekundären Speicherressourcen zu erstellen, führen Datenbank- und Storage-Administratoren folgende Aktionen durch.

|===
| Ihr Ziel ist | Dann... 


 a| 
Erstellen oder bearbeiten Sie ein Profil
 a| 
So erstellen oder bearbeiten Sie ein Profil:

* Backup-Sicherung für den sekundären Storage
* Wenn Sie Data ONTAP 7-Mode verwenden und Protection Manager installiert haben, können Sie die Richtlinien auswählen, die vom Storage- oder Backup-Administrator in Protection Manager erstellt wurden.
+
Wenn Sie Data ONTAP in 7-Mode verwenden und der Schutz aktiviert ist, erstellt SnapManager einen Datensatz für die Datenbank. Ein Datenset besteht aus einer Sammlung von Storage Sets und Konfigurationsinformationen, die ihren Daten zugeordnet sind. Zu den mit einem Datensatz verknüpften Speichersätzen zählen ein primärer Speichersatz für den Export von Daten auf Clients sowie der Satz an Replikaten und Archiven, die sich auf anderen Speichergruppen befinden. Datensätze stellen exportierbare Anwenderdaten dar. Wenn der Administrator den Schutz für eine Datenbank deaktiviert, löscht SnapManager den Datensatz.

* Wenn Sie ONTAP verwenden, müssen Sie je nach erstellten SnapMirror oder SnapVault Beziehung entweder die Richtlinie _SnapManager_cDOT_Mirror_ oder _SnapManager_cDOT_Vault_ auswählen.


Wenn Sie den Sicherungsschutz deaktivieren, wird eine Warnmeldung angezeigt, die angibt, dass der Datensatz gelöscht wird und die Wiederherstellung oder das Klonen von Backups für dieses Profil nicht möglich ist.



 a| 
Profil anzeigen
 a| 
Da der Storage-Administrator noch keine Storage-Ressourcen zur Implementierung der Sicherungsrichtlinie zugewiesen hat, wird das Profil sowohl in der grafischen SnapManager Benutzeroberfläche als auch in der Ausgabe des Profils als nicht konform angezeigt.



 a| 
Weisen Sie Storage-Ressourcen in der Protection Manager Management Console zu
 a| 
In der Protection Manager Management-Konsole zeigt der Storage-Administrator den ungeschützten Datensatz an und weist jedem Node des Datensatzes, der dem Profil zugeordnet ist, einen Ressourcen-Pool zu. Der Storage-Administrator stellt dann sicher, dass sekundäre Volumes bereitgestellt und Sicherungsbeziehungen initialisiert werden.



 a| 
Sehen Sie sich das entsprechende Profil in SnapManager an
 a| 
In SnapManager erkennt der Datenbankadministrator, dass sich das Profil sowohl in der grafischen Benutzeroberfläche als auch in der Befehlsausgabe des Profils in den Status „formant“ geändert hat, was bedeutet, dass Ressourcen zugewiesen wurden.



 a| 
Erstellen Sie das Backup
 a| 
* Wählen Sie das vollständige Backup aus.
* Wählen Sie außerdem aus, ob das Backup geschützt werden soll, und wählen Sie die primäre Aufbewahrungsklasse (z. B. stündlich oder täglich) aus.
* Wenn Sie Data ONTAP in 7-Mode verwenden und das Backup sofort auf sekundärem Storage schützen möchten, der den Protection Manager-Schutzzeitplan überwählt, geben Sie die Option -protectnow an.
* Wenn Sie ONTAP verwenden und das Backup sofort auf dem sekundären Storage schützen möchten, geben Sie die Option „Schutz“ an.
+

NOTE: Die Option zum Schutz ist in Clustered Data ONTAP nicht verfügbar.





 a| 
Backup anzeigen
 a| 
Das neue Backup wird als geplant für den Schutz angezeigt, aber noch nicht geschützt (in der SnapManager-Schnittstelle und in der Ausgabe des Backup show-Befehls). Der Schutzstatus wird als „`not protected`“ angezeigt.



 a| 
Zeigen Sie die Sicherungsliste an
 a| 
Nachdem der Storage-Administrator überprüft hat, ob das Backup in den sekundären Speicher kopiert wurde, ändert SnapManager den Sicherungsstatus von „`not protected`“ in „`protected`“.

|===