---
permalink: unix-administration/concept_requirements_for_using_databases_with_nfs_and_snapmanager.html 
sidebar: sidebar 
keywords: requirement, network, file, system, nfs, snapmanager, recommendation, solaris, aix, linux, actimeo=0 
summary: 'Sie müssen die Anforderungen für die Verwendung von Datenbanken mit Network File System (NFS) und SnapManager kennen. Die Empfehlungen umfassen die Ausführung als root, Attribut-Caching und symbolische Links.' 
---
= Anforderungen für die Verwendung von Datenbanken mit NFS und SnapManager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Anforderungen für die Verwendung von Datenbanken mit Network File System (NFS) und SnapManager kennen. Die Empfehlungen umfassen die Ausführung als root, Attribut-Caching und symbolische Links.

* Sie müssen SnapManager als Root ausführen. SnapManager muss auf die Dateisysteme zugreifen können, die Datendateien, Kontrolldateien, Online-Wiederherstellungsprotokolle, Archivprotokolle und den Datenbank-Home enthalten.
+
Legen Sie eine der folgenden NFS-Exportoptionen fest, um sicherzustellen, dass Root auf die Dateisysteme zugreifen kann:

+
** Root=Hostname
** rw=Host-Name, anon=0


* Sie müssen das Attribut-Caching für alle Volumes deaktivieren, die Datenbankdatendateien, Kontrolldateien, Redo- und Archivprotokolle und die Datenbank-Startseite enthalten.
+
Exportieren Sie die Volumes mithilfe der optionen noac (für Solaris und AIX) oder actimeo=0 (für Linux).

* Sie müssen die Datenbankdatendateien aus dem lokalen Speicher mit NFS verknüpfen, um nur symbolische Links auf Mount-Punkt-Ebene zu unterstützen.

