---
permalink: unix-administration/concept_snapmanger_limitations_for_clustered_data_ontap.html 
sidebar: sidebar 
keywords: limitations, functionalities, snapmanager, operations, ontap, cluster, data 
summary: Sie müssen die Einschränkungen für einige Funktionalitäten und SnapManager-Vorgänge kennen, wenn Sie Clustered Data ONTAP verwenden. 
---
= SnapManager Limitierungen für Clustered Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen die Einschränkungen für einige Funktionalitäten und SnapManager-Vorgänge kennen, wenn Sie Clustered Data ONTAP verwenden.

Die folgenden Funktionalitäten werden nicht unterstützt, wenn Sie SnapManager auf Clustered Data ONTAP nutzen:

* Datensicherungsfunktionen, wenn SnapManager in OnCommand Unified Manager integriert ist
* Eine Datenbank, in der eine LUN zu einem System gehört, auf dem Data ONTAP 7-Mode und die andere LUN ausgeführt werden, gehört zu einem System mit Clustered Data ONTAP
* SnapManager für Oracle unterstützt keine Migration von Vserver, wie sie von Clustered Data ONTAP nicht unterstützt wird
* SnapManager für Oracle unterstützt die Funktion Clustered Data ONTAP 8.2.1 nicht zur Festlegung verschiedener Exportrichtlinien für Volumes und qtrees

