---
permalink: unix-administration/concept_how_to_collect_dump_files.html 
sidebar: sidebar 
keywords: -dump, snapmanager, command, collect, dump, file, successful, fail, creating, updating, verify 
summary: Sie können -dump in den SnapManager-Befehl einschließen, um die Dump-Dateien nach einem erfolgreichen oder fehlgeschlagenen SnapManager-Vorgang zu sammeln. 
---
= So sammeln Sie Speicherauszugsdateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können -dump in den SnapManager-Befehl einschließen, um die Dump-Dateien nach einem erfolgreichen oder fehlgeschlagenen SnapManager-Vorgang zu sammeln.

Sie können Dump-Dateien für die folgenden SnapManager-Vorgänge sammeln:

* Profile werden erstellt
* Profile werden aktualisiert
* Backups werden erstellt
* Backups werden überprüft
* Backups werden gelöscht
* So werden Backups entlastet
* Montage von Backups
* UnMounten von Backups
* Backups werden wiederhergestellt
* Klone werden erstellt
* Klone werden gelöscht
* Aufteilung von Klonen



NOTE: Wenn Sie ein Profil erstellen, können Sie Dump-Dateien nur sammeln, wenn der Vorgang erfolgreich ist. Wenn beim Erstellen eines Profils ein Fehler auftritt, müssen Sie den Befehl „Smosystem dump“ verwenden. Für erfolgreiche Profile können Sie die SmoOperation Dump und smoprofile Dump-Befehle verwenden, um die Dump-Dateien zu sammeln.

*Beispiel*

[listing]
----

      smo  backup create -profile targetdb1_prof1 -auto -full -online -dump
----