---
permalink: unix-administration/reference_the_smosmsapcredential_set_command.html 
sidebar: sidebar 
keywords: command, credentials, user, access, secure, resource, host, repositories, database, profile, specified, argument, smo 
summary: Mit diesem Befehl können Sie die Anmeldeinformationen für Benutzer festlegen, die auf sichere Ressourcen wie Hosts, Repositorys und Datenbankprofile zugreifen können. Das Hostpasswort ist das Passwort des Benutzers auf dem Host, auf dem SnapManager ausgeführt wird. Das Repository-Kennwort ist das Kennwort des Oracle-Benutzers, der das SnapManager-Repository-Schema enthält. Das Profilkennwort ist ein Passwort, das von der Person, die das Profil erstellt, gebildet wird. Wenn bei den Host- und Repository-Optionen die Option optional -password nicht enthalten ist, werden Sie aufgefordert, ein Kennwort des in den Befehlsargumenten angegebenen Typs einzugeben. 
---
= Der Befehl Smo Credential Set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl können Sie die Anmeldeinformationen für Benutzer festlegen, die auf sichere Ressourcen wie Hosts, Repositorys und Datenbankprofile zugreifen können. Das Host-Passwort ist das Passwort des Benutzers auf dem Host, auf dem SnapManager ausgeführt wird. Das Repository-Kennwort ist das Kennwort des Oracle-Benutzers, der das SnapManager-Repository-Schema enthält. Das Profilkennwort ist ein Passwort, das von der Person, die das Profil erstellt, gebildet wird. Wenn bei den Host- und Repository-Optionen die Option optional -password nicht enthalten ist, werden Sie aufgefordert, ein Kennwort des in den Befehlsargumenten angegebenen Typs einzugeben.



== Syntax

[listing]
----

        smo credential set
\[-host
-name host_name
-username username\]
\[-password password\] \] \|
\[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username\] \[-password repo_password\] \]
-port repo_port \|
\[-profile
-name profile_name\]
\[-password password\] \]
\[-quiet \| -verbose\]
----


== Parameter

* *-Host-Hostname*
+
Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem SnapManager ausgeführt wird.

+
Der Parameter -Host enthält die folgenden Optionen:

+
** -Name Host_Name: Gibt den Namen des Hosts an, für den Sie das Passwort festlegen möchten.
** -Username user_Name: Gibt den Benutzernamen auf dem Host an.
** -Password password: Gibt das Passwort des Benutzers auf dem Host an.


* *-Repository -dbname*
+
Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

+
Der Parameter -Repository enthält die folgenden Optionen:

+
** -Dbnamerepo_Service_Name: Gibt den Namen der Datenbank an, die das Profil speichert. Verwenden Sie entweder den globalen Namen oder den SID.
** -Host repo_Host: Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem die Repository-Datenbank ausgeführt wird.
** -Login-username repo_username: Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank erforderlich ist, in der das Repository gespeichert ist.
** -Password password: Gibt das Kennwort an, das für den Zugriff auf die Datenbank, die das Repository speichert, erforderlich ist.
** -Port repo_Port: Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.


* *-profile -Name profile_Name*
+
Gibt das Profil an, mit dem die Datenbank verknüpft ist.

+
Der Parameter -profile enthält die folgende Option:

+
** -Name profilname: Gibt den Namen des Profils an, für das Sie das Passwort festlegen.
** -Password password: Gibt das Passwort an, das für den Zugriff auf das Profil erforderlich ist.


* *-ruhig*
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl zum Festlegen von Repository-Anmeldedaten

Im folgenden Beispiel werden Anmeldeinformationen für ein Repository festgelegt.

[listing]
----

smo credential set -repository -dbname SMOREPO -host hotspur -port 1521 -login -username chris
Password for chris@hotspur:1521/SMOREPO : ********
Confirm password for chris@hotspur:1521/SMOREPO : ********
----
[listing]
----
SMO-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMO-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== Beispiel-Befehl zum Festlegen von Host-Anmeldedaten

Da eine Hostanmeldeinformationen eine tatsächliche Betriebssystemanmeldeinformationen darstellen, muss sie zusätzlich zum Passwort den Benutzernamen enthalten.

[listing]
----
smo credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----
*Verwandte Informationen*

xref:concept_snapmanager_security.adoc[Wie SnapManager die Sicherheit gewährleistet]
