---
permalink: unix-administration/reference_how_to_locate_dump_files.html 
sidebar: sidebar 
keywords: dump, file, locate, client, system, easy, access, file, helpful, troubleshoot 
summary: Die Dump-Datei befindet sich im Client-System für einfachen Zugriff. Diese Dateien sind hilfreich, wenn Sie Probleme im Zusammenhang mit Profil, System oder einer beliebigen Operation beheben müssen. 
---
= So finden Sie Speicherauszugsdateien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Dump-Datei befindet sich im Client-System für einfachen Zugriff. Diese Dateien sind hilfreich, wenn Sie Probleme im Zusammenhang mit Profil, System oder einer beliebigen Operation beheben müssen.

Die Dump-Datei befindet sich im Home-Verzeichnis des Benutzers auf dem Client-System.

* Wenn Sie die grafische Benutzeroberfläche (GUI) verwenden, befindet sich die Dump-Datei unter:
+
[listing]
----
user_home/Application Data/NetApp/smo/3.3.0/smo_dump dump_file_type_name
server_host.jar
----
* Wenn Sie die Befehlszeilenschnittstelle (CLI) verwenden, befindet sich die Dump-Datei unter:
+
[listing]
----
user_home/.netapp/smo/3.3.0/smo_dump_dump_file_type_name server_host.jar
----


Die Dump-Datei enthält die Ausgabe des Dump-Befehls. Der Name der Datei hängt von den angegebenen Informationen ab. In der folgenden Tabelle werden die Typen von Dump-Operationen und die daraus resultierenden Dateinamen angezeigt:

|===
| Typ des Speicherauszugsvorgangs | Dateiname wird angezeigt 


 a| 
Befehl für den Operation Dump mit Vorgangs-ID
 a| 
smo_dump_operation-id.jar



 a| 
Der Befehl für den Operation Dump enthält keine Vorgangs-ID
 a| 
smo Operation Dump -Profile VH1-verbose die folgende Ausgabe wird angezeigt:

[listing]
----
smo operation dump -profile VH1 -verbose
[ INFO] SMO-13048: Dump Operation Status: SUCCESS
[ INFO] SMO-13049: Elapsed Time: 0:00:01.404
Dump file created.
Path: /oracle/VH1/<path>/smo/3.3.0/smo_dump_VH1_kaw.rtp.foo.com.jar
----


 a| 
Befehl für System Dump
 a| 
smo_dump_host-name.jar



 a| 
Profildump-Befehl
 a| 
smo_dump_profile-name_host-name.jar

|===