---
permalink: unix-administration/reference_the_smosmsaprepository_delete_command.html 
sidebar: sidebar 
keywords: command, delete, repository, store, database, profile, associate, credentials, smo 
summary: Mit diesem Befehl wird ein Repository gelöscht, das zum Speichern von Datenbankprofilen und zugehörigen Anmeldedaten verwendet wird. Sie können ein Repository nur löschen, wenn kein Profil im Repository vorhanden ist. 
---
= Der Befehl smo Repository löschen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl wird ein Repository gelöscht, das zum Speichern von Datenbankprofilen und zugehörigen Anmeldedaten verwendet wird. Sie können ein Repository nur löschen, wenn kein Profil im Repository vorhanden ist.



== Syntax

[listing]
----

        smo repository delete
-repository
-port repo_port
-dbname repo_service_name
-host repo_host
-login -username repo_username
[-force] [-noprompt]
[-quiet | -verbose]
----


== Parameter

* *-Repository*
+
Die Optionen, die dem -Repository folgen, geben die Details der Datenbank für das Repository an.

* *-Port repo_Port*
+
Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.

* *-dbname repo_Service_Name*
+
Gibt den Namen der Datenbank an, in der das Repository gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

* *-Host repo_Host*
+
Gibt den Namen oder die IP-Adresse des Hostcomputers an, auf dem die Repository-Datenbank ausgeführt wird.

* *-Login*
+
Startet die Repository-Anmeldedaten.

* *-username repo_username*
+
Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank erforderlich ist, in der das Repository gespeichert ist.

* *-Force*
+
Versucht, das Löschen des Repositorys zu erzwingen, auch wenn unvollständige Vorgänge vorliegen. SnapManager gibt eine Eingabeaufforderung aus, wenn unvollständige Vorgänge vorliegen. Sie werden gefragt, ob Sie das Repository wirklich löschen möchten.

* *-noprompt*
+
Fordert Sie nicht auf, bevor Sie das Repository löschen. Mit der Option -noprompt wird sichergestellt, dass die Eingabeaufforderung nicht angezeigt wird. Dies erleichtert das Löschen von Repositorys mit einem Skript.

* *-ruhig*
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Befehlsbeispiel

Im folgenden Beispiel wird das Repository in der SALESDB-Datenbank gelöscht.

[listing]
----
smo repository delete -repository -port 1521 -dbname smorep
-host nila -login -username smofresno -force -verbose
This command will delete repository "smofresno@smorep/nila".
Any resources maintained by the repository must be cleaned up manually.
This may include snapshots, mounted backups, and clones.
Are you sure you wish to proceed (Y/N)?Y
[ INFO] SMO-09201: Dropping existing schema as smofresno
  on jdbc:oracle:thin:@//nila:1521/smorep.
[ INFO] SMO-13048: Repository Delete Operation Status: SUCCESS
[ INFO] SMO-13049: Elapsed Time: 0:00:06.372
[ INFO] SMO-20010: Synchronizing mapping for profiles in
   repository "smofresno@smorep/nila:1521".
[ WARN] SMO-20029: No repository schema exists in "smofresno@smorep/nila:1521".
 Deleting all profile mappings for this repository.
[ INFO] SMO-20012: Deleted stale mapping for profile "TESTPASS".
----