---
permalink: unix-administration/reference_the_smosmsapoperation_list_command.html 
sidebar: sidebar 
keywords: command, list, summary, information, operation, record, specified, profile, smo 
summary: Mit diesem Befehl werden die Zusammenfassungsinformationen aller Vorgänge aufgelistet, die für ein bestimmtes Profil aufgezeichnet wurden. 
---
= Befehl smo Operation list
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl werden die Zusammenfassungsinformationen aller Vorgänge aufgelistet, die für ein bestimmtes Profil aufgezeichnet wurden.



== Syntax

[listing]
----

        smo operation list
-profile profile_name
\[-delimiter character\]
\[-quiet \| -verbose\]
----


== Parameter

* *-profile Profile_Name*
+
Gibt den Namen des Profils an. Dieser Name kann bis zu 30 Zeichen lang sein und muss innerhalb des Hosts eindeutig sein.

* *-Trennzeichen*
+
(Optional) Wenn dieser Parameter angegeben wird, listet der Befehl jede Zeile in einer separaten Zeile auf und die Attribute in dieser Zeile werden durch das angegebene Zeichen getrennt.

* *-ruhig*
+
(Optional) zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
(Optional) zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl

Im folgenden Beispiel werden die Zusammenfassungsinformationen aller Vorgänge aufgeführt, die mit dem angegebenen Profil protokolliert wurden.

[listing]
----
smo operation list -profile myprofile
----
[listing]
----
Start Date Status Operation ID Type Host
-------------------- ---------- -------------------------------- ------------------ --
2007-07-16 16:03:57 SUCCESS 8abc01c813d0a1530113d0a15c5f0005 Profile Create Host3
2007-07-16 16:04:55 FAILED 8abc01c813d0a2370113d0a241230001 Backup Host3
2007-07-16 16:50:56 SUCCESS 8abc01c813d0cc580113d0cc60ad0001 Profile Update Host3
2007-07-30 15:44:30 SUCCESS 8abc01c81418a88e011418a8973e0001 Remove Backup Host3
2007-08-10 14:31:27 SUCCESS 8abc01c814510ba20114510bac320001 Backup Host3
2007-08-10 14:34:43 SUCCESS 8abc01c814510e9f0114510ea98f0001 Mount Host3
2007-08-10 14:51:59 SUCCESS 8abc01c814511e6e0114511e78d40001 Unmount Host3
----
*Verwandte Informationen*

xref:task_viewing_a_list_of_operations.adoc[Anzeigen einer Liste von Vorgängen]
