---
permalink: unix-administration/reference_the_smosmsap_clone_split_command.html 
sidebar: sidebar 
keywords: clone, split, command, independent, original, snapmanager 
summary: Sie können den Befehl Clone Split ausführen, um einen Klon aufzuteilen. Der Split-Klon ist unabhängig vom ursprünglichen Klon. SnapManager generiert nach der Teilung des Klons ein neues Profil, und Sie können dieses Profil zum Verwalten des Split-Klons verwenden. 
---
= Der Befehl smo Clone Split
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Befehl Clone Split ausführen, um einen Klon aufzuteilen. Der Split-Klon ist unabhängig vom ursprünglichen Klon. SnapManager generiert nach der Teilung des Klons ein neues Profil, und Sie können dieses Profil zum Verwalten des Split-Klons verwenden.



== Syntax

[listing]
----

        smo clone split
-profile clone-profile
\[-host hostname\]
\{-label clone-label | -id clone-id\} \[-split-label split-operation_label\]
\[-comment comment\]
-new-profile new-profile-name \[-profile-password new-profile_password\]
-repository -dbname repo_service_name
-host repo_host
-port repo_port
-login -username repo_username
-database -dbname db_dbname
-host db_host \[-sid db_sid\] \[-login -username db_username -password db_password
-port db_port\]
\[-rman \{\{-controlfile \| \{-login -username rman_username
-password rman_password\} -tnsname rman_tnsname\}\}\]
-osaccount osaccount
-osgroup osgroup
\[-retain
\[-hourly \[-count n\] \[-duration  m\]\]
\[-daily \[-count n\] \[-duration m\]\]
\[-weekly  \[-count n\] \[-duration m\]\]
\[-monthly \[-count n\] \[-duration m\]\] \]
\[-profile-comment profile-comment\]
\[-snapname-pattern pattern\]
\[-protect \[-protection-policy policy_name\]\] \| \[-noprotect\]\]
\[-summary-notification
\[-notification
\[-success -email email_address1,email_address2
-subject subject-pattern\]
\[failure -email email_address1,email_address2
-subject subject-pattern\] \]
[-separate-archivelog-backups
-retain-archivelog-backups
 -hours  hours |
-days days |
-weeks weeks |
-months months
[-protect \[-protection-policy policy_name \| -noprotect]
[-include-with-online-backups \| -no-include-with-online-backups]]
[-dump]
\[-quiet \| -verbose\]
----


== Parameter

* *-Profil Clone-Profil*
+
Gibt den Profilnamen an, aus dem der Klon erstellt wird.

* *-Host-Hostname*
+
Gibt den Host-Namen an, in dem der Klon vorhanden ist.

* *-Label Clone-Label*
+
Gibt den vom Klonvorgang erzeugten Namen an.

* *-id Clone-id*
+
Gibt die eindeutige ID an, die vom Klonvorgang generiert wird.

* *-Split-Label Split-Operation_Label*
+
Gibt den vom Klonvorgang erzeugten Namen an.

* *-New-profile New-profile_Name*
+
Gibt den neuen Profilnamen an, den SnapManager nach einem erfolgreichen Split-Vorgang generieren wird.

* *-profile-password New-profile_password*
+
Gibt das Kennwort für das Profil an.

* *-Repository*
+
Gibt die Details der Datenbank für das Repository an.

* *-dbname repo_Service_Name*
+
Gibt den Namen der Datenbank an, in der das Repository gespeichert wird. Sie können entweder den globalen Namen oder die Systemkennung verwenden.

* *-Host repo_Host*
+
Gibt den Namen oder die IP-Adresse des Hostcomputers an, auf dem sich die Repository-Datenbank befindet.

* *-Port repo_Port*
+
Gibt die TCP-Portnummer (Transmission Control Protocol) an, die für den Zugriff auf den Host verwendet wird, auf dem sich die Repository-Datenbank befindet.

* *-Login*
+
Gibt die Anmeldedaten für das Repository an. Dies ist optional. Wenn nicht angegeben, verwendet SnapManager standardmäßig den Verbindungsmodus für OS-Authentifizierung.

* *-username repo_username*
+
Gibt den Benutzernamen an, der für den Zugriff auf den Host benötigt wird, auf dem sich die Repository-Datenbank befindet.

* *-Datenbank*
+
Gibt die Details der Datenbank an, die gesichert, wiederhergestellt oder geklont werden soll.

* *-dbname db_dbname*
+
Gibt den Namen der Datenbank an, die das Profil beschreibt. Sie können entweder den globalen Namen oder die Systemkennung verwenden.

* *-Host db_Host*
+
Gibt den Namen oder die IP-Adresse des Hostcomputers an, auf dem sich die Datenbank befindet.

* *-sid db_sid*
+
Gibt die Systemkennung der Datenbank an, die das Profil beschreibt. Standardmäßig verwendet SnapManager den Datenbanknamen als Systemkennung. Falls sich die Systemkennung vom Datenbanknamen unterscheidet, müssen Sie sie mit der Option -sid angeben.

+
Wenn Sie beispielsweise Oracle Real Application Clusters (RAC) verwenden, müssen Sie die Systemkennung der RAC-Instanz auf dem RAC-Knoten angeben, von dem aus SnapManager ausgeführt wird.

* *-Login*
+
Gibt die Anmeldedaten für die Datenbank an.

* *-username db_username*
+
Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank erforderlich ist, die das Profil beschreibt.

* *-Passwort db_password*
+
Gibt das Kennwort an, das für den Zugriff auf die Datenbank erforderlich ist, die das Profil beschreibt.

* *-rman*
+
Gibt die Details an, die SnapManager zum Katalogisieren von Backups mit dem Oracle Recovery Manager (RMAN) verwendet.

* *-controlfile*
+
Gibt die Steuerdateien der Zieldatenbank als RMAN-Repository anstelle eines Katalogs an.

* *-Login*
+
Gibt die RMAN-Anmeldedaten an.

* *-Passwort rman_password*
+
Gibt das Kennwort an, mit dem Sie sich beim RMAN-Katalog anmelden können.

* *-username rman_Benutzername*
+
Gibt den Benutzernamen an, der zum Anmelden beim RMAN-Katalog verwendet wird.

* *-tnsname tnsname*
+
Gibt den Verbindungsnamen tnsname an (dieser wird in der Datei tsname.ora definiert).

* *-osaccount osconcount*
+
Gibt den Namen des Benutzerkontos für die Oracle-Datenbank an. SnapManager verwendet dieses Konto, um die Oracle-Vorgänge wie dem Starten und Herunterfahren durchzuführen. Normalerweise ist es der Benutzer, der die Oracle-Software auf dem Host besitzt, zum Beispiel oracle.

* *-osgroup osgroup*
+
Gibt den Namen der Oracle-Datenbankgruppe an, die dem oracle-Konto zugeordnet ist.

+

NOTE: Die Variablen -osaccount und -osgroup sind für UNIX erforderlich, jedoch nicht zulässig für Datenbanken, die unter Windows ausgeführt werden.

* *-halten [-hourly [-count n] [-duration m] [-taily [-count n] [-duration m]] [-Weekly [-count n] [-duration m]] [-monthly [-count n] [-duration m]]*
+
Gibt die Aufbewahrungsrichtlinie für ein Backup an.

+
Für jede Aufbewahrungsklasse kann entweder der Aufbewahrungszähler oder die Aufbewahrungsdauer angegeben werden. Die Dauer ist in Einheiten der Klasse (z. B. Stunden für Stunde, Tage für Tag). Wenn Sie beispielsweise nur eine Aufbewahrungsdauer von 7 für tägliche Backups angeben, wird SnapManager die Anzahl der täglichen Backups für das Profil nicht begrenzen (da die Aufbewahrungsanzahl 0 ist), aber SnapManager löscht automatisch tägliche Backups, die vor über 7 Tagen erstellt wurden.

* *-profile-comment Profil-comment*
+
Gibt den Kommentar für ein Profil an, das die Profildomäne beschreibt.

* *-snapname-Muster*
+
Gibt das Benennungsmuster für Snapshot Kopien an. Außerdem können Sie in allen Namen von Snapshot Kopien benutzerdefinierten Text einfügen, beispielsweise HAOPS für hochverfügbare Vorgänge. Sie können das Benennungsmuster der Snapshot Kopie ändern, wenn Sie ein Profil erstellen oder nachdem das Profil erstellt wurde. Das aktualisierte Muster gilt nur für Snapshot Kopien, die noch nicht erstellt wurden. Snapshot Kopien, die vorhanden sind, behalten das vorherige SnapName-Muster bei. Sie können mehrere Variablen im Mustertext verwenden.

* *-protect -Protection-Policy_Name*
+
Gibt an, ob das Backup auf dem sekundären Speicher gesichert werden soll.

+

NOTE: Wenn -protect ohne -Protection-Policy angegeben wird, dann hat der Datensatz keine Schutzpolitik. Wenn -protect angegeben wird und -Protection-Policy nicht gesetzt wird, wenn das Profil erstellt wird, dann kann es später durch den smo profile Update Befehl oder durch den Storage Administrator über die Protection Manager Konsole gesetzt werden.

* *-summary-notification*
+
Gibt die Details zur Konfiguration einer E-Mail-Benachrichtigung für mehrere Profile unter einer Repository-Datenbank an. SnapManager generiert diese E-Mail.

* *-Benachrichtigung*
+
Gibt die Details zur Konfiguration der E-Mail-Benachrichtigung für das neue Profil an. SnapManager generiert diese E-Mail. Die E-Mail-Benachrichtigung ermöglicht es dem Datenbankadministrator, E-Mails über den Status erfolgreich oder fehlgeschlagen des Datenbankvorgangs zu erhalten, der mit diesem Profil ausgeführt wird.

* *-Erfolg*
+
Gibt an, dass die E-Mail-Benachrichtigung für ein Profil aktiviert ist, für das der SnapManager-Vorgang erfolgreich ist.

* *-email address 1 email address 2*
+
Gibt die E-Mail-Adresse des Empfängers an.

* *-Betreff-Muster*
+
Gibt den Betreff für die E-Mail an.

* *-Versagen*
+
Gibt an, dass die E-Mail-Benachrichtigung für ein Profil aktiviert ist, für das der SnapManager-Vorgang fehlschlägt.

* *-separate-archivlog-Backups*
+
Gibt an, dass die Backup des Archivprotokolls von der Datendatei-Sicherung getrennt ist. Dies ist ein optionaler Parameter, den Sie bei der Erstellung des Profils angeben können. Nachdem die Backups mit dieser Option getrennt wurden, können Sie entweder nur Datendateien Backup oder ausschließlich Archivprotokolle erstellen.

* *-behalten-archivelog-Backups -Stunden- -Tage- Wochen- Monthsmonths*
+
Gibt an, dass die Archiv-Log-Backups auf Basis der Aufbewahrungsdauer des Archivprotokolls (stündlich, täglich, wöchentlich oder monatlich) aufbewahrt werden.

* *Schutz [-Schutz-policypolicy_Name] -noprotect*
+
Gibt an, dass die Archivprotokolldateien auf der Grundlage der Archivierungsprotokollschutzrichtlinie geschützt sind.

+
Gibt an, dass die Archivprotokolldateien nicht mit der Option -noprotect geschützt sind.

* *-enthalten-mit-online-Backups*
+
Gibt an, dass das Backup des Archivprotokolls zusammen mit dem Online-Datenbank-Backup enthalten ist.

+
Gibt an, dass die Archiv-Log-Backups nicht zusammen mit dem Online-Datenbank-Backup enthalten sind.

* *-dump*
+
Gibt an, dass die Dump-Dateien nach dem erfolgreichen Erstellen des Profils nicht erfasst werden.

* *-ruhig*
+
Zeigt nur Fehlermeldungen in der Konsole an. Die Standardeinstellung zeigt Fehler- und Warnmeldungen an.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an.


