---
permalink: unix-administration/reference_the_smosmsapcredential_delete_command.html 
sidebar: sidebar 
keywords: command, delete, user, credential, particular, secure, resource, smo 
summary: Mit diesem Befehl werden die Benutzeranmeldeinformationen für eine bestimmte gesicherte Ressource gelöscht. 
---
= Der Befehl zum Löschen von Smo-Anmeldeinformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl werden die Benutzeranmeldeinformationen für eine bestimmte gesicherte Ressource gelöscht.



== Syntax

[listing]
----

        smo credential delete
\[-host -name host_name
-username username\] \|
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username
-port repo_port\] \|
\[-profile
-name profile_name\]
[-quiet | -verbose]
----


== Parameter

* *-Host-Hostname*
+
Gibt den Namen des Host-Servers an, auf dem SnapManager ausgeführt wird.

+
Der Parameter -Host enthält die folgenden Optionen:

+
** -Name Host_Name: Gibt den Namen des Hosts an, für den Sie das Passwort löschen möchten.
** -Username user_Name: Gibt den Benutzernamen auf dem Host an.


* *-Repository -dbname*
+
Gibt den Namen der Datenbank an, in der das Profil gespeichert wird. Verwenden Sie entweder den globalen Namen oder den SID.

+
Der Parameter -Repository enthält die folgenden Optionen:

+
** -Dbnamerepo_Service_Name: Gibt den Namen der Datenbank an, die das Profil speichert. Verwenden Sie entweder den globalen Namen oder den SID.
** -Host repo_Host: Gibt den Namen oder die IP-Adresse des Hostservers an, auf dem die Repository-Datenbank ausgeführt wird.
** -Login-username repo_username: Gibt den Benutzernamen an, der für den Zugriff auf die Datenbank erforderlich ist, in der das Repository gespeichert ist.
** -Port repo_Port: Gibt die TCP-Portnummer an, die für den Zugriff auf die Datenbank verwendet wird, in der das Repository gespeichert ist.


* *-profile -Name profile_Name*
+
Gibt das Profil an, mit dem die Datenbank verknüpft ist.

+
Der Parameter -profile enthält die folgende Option:

+
** -Name profilname: Gibt den Namen des Profils an, für das Sie das Passwort löschen werden.


* *-ruhig*
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl

In diesem Beispiel werden die Anmeldeinformationen des Profils gelöscht.

[listing]
----
smo credential delete -profile -name user1 -verbose
----
[listing]
----
SMO-20022 [INFO ]: Deleted credentials and repository mapping
 for profile "user1" in user credentials for "user1".
----
In diesem Beispiel werden die Anmeldeinformationen des Repositorys gelöscht.

[listing]
----
smo credential delete -repository -dbname SMOREPO -host Host2
-login -username user1 -port 1521
----
[listing]
----
SMO-20023 [INFO ]: Deleted repository credentials for "user1@SMOREPO/wasp:1521"
and associated profile mappings in user credentials for "user1".
----
In diesem Beispiel werden die Anmeldeinformationen des Hosts gelöscht.

[listing]
----
smo credential delete -host -name Host2
----
[listing]
----
SMO-20033 [INFO ]: Deleted host credentials for "Host2" in user credentials for "user1".
----
*Verwandte Informationen*

xref:task_deleting_credentials_for_individual_resources.adoc[Löschen von Anmeldeinformationen für einzelne Ressourcen]
