---
permalink: unix-administration/reference_troubleshooting_snapmanager.html 
sidebar: sidebar 
keywords: information, common, issue, resolve, troubleshoot, snapmanager 
summary: Hier finden Sie Informationen über einige der häufigsten Probleme, die auftreten können, und über deren Behebung. 
---
= SnapManager zur Fehlerbehebung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hier finden Sie Informationen über einige der häufigsten Probleme, die auftreten können, und über deren Behebung.

In der folgenden Tabelle werden häufige Probleme und mögliche Lösungen beschrieben:

|===
| Frage, die nur mit Problemen zu tun hat | Mögliche Lösung 


 a| 
Werden die Zieldatenbank und der Listener ausgeführt?
 a| 
Führen Sie den Befehl lsnrctl Status aus. Stellen Sie sicher, dass die Datenbankinstanz beim Listener registriert ist.



 a| 
Ist der Storage sichtbar?
 a| 
Führen Sie den befehl SnapDrive Storage show -all aus.



 a| 
Ist der Storage beschreibbar?
 a| 
Bearbeiten Sie eine Datei im Bereitstellungspunkt, den Sie gerade erstellt haben. Verwenden Sie den Befehl touch filename. Wenn die Datei erstellt wird, ist Ihr Speicher beschreibbar. Sie müssen sicherstellen, dass der Speicher vom Benutzer beschreibbar ist, auf dem SnapManager ausgeführt wird (z. B. als Root auf UNIX).



 a| 
Wird der SnapManager Server ausgeführt?
 a| 
Führen Sie smo_Server Status aus und versuchen Sie, den Server mit dem Befehl smo_Server Start zu starten.

Bevor Sie SnapManager-Befehle für Profile mit der grafischen Benutzeroberfläche (GUI) oder der Befehlszeilenschnittstelle (CLI) initiieren können, muss der Server ausgeführt werden. Sie können Repositorys erstellen oder aktualisieren, ohne den Server zu starten. Um jedoch alle anderen SnapManager-Vorgänge auszuführen, muss der Server ausgeführt werden.

Geben Sie zum Starten des SnapManager-Servers den folgenden Befehl ein: smo_Server starte.



 a| 
Sind alle Komponenten erforderlich, um SnapManager korrekt auszuführen?
 a| 
Führen Sie den smo System verify Befehl aus, um zu überprüfen, dass SnapDrive korrekt eingerichtet ist.



 a| 
Verfügen Sie über die richtige Version von SnapManager?
 a| 
Verwenden Sie den Befehl smo Version, um die SnapManager-Version zu überprüfen.



 a| 
Haben Sie sich die Protokolldateien von SnapManager angesehen, um zu ermitteln, ob die Fehlermeldungen helfen können, das Problem zu isolieren?
 a| 
SnapManager zeichnet alle Log-Einträge in einem Satz rotierender Log-Dateien auf. Die Protokolldateien finden Sie unter /var/log/smo.

Die Log-Dateien sind unter C:\Program_Files\NetApp\SnapManager für Oracle\logs zu finden.

Es könnte auch hilfreich sein, sich die Protokolle an folgender Stelle anzusehen:

/Usr_Home/.netapp/smo/3.3.0/log/

Jedes Betriebsprotokoll wird in seine eigene Protokolldatei der Form smo_of_date_time.log geschrieben.



 a| 
Wenn auf einem Storage-System, auf dem Data ONTAP nicht ausgeführt wird, Archivprotokolle gespeichert sind, haben Sie diese von Überlegungen für Backups mit SnapManager ausgeschlossen?
 a| 
Mit der Datei smo.config können Sie bestimmte Archiv-Log-Dateien ausschließen. Für UNIX befinden sich die Dateien an folgender Stelle: /Opt/NetApp/smo/Properties/smo.config

Verwenden Sie das in der Datei erwähnte Format, um die lokalen Archivprotokolle auszuschließen. Weitere Informationen finden Sie im Thema „`SBenetzungskonfigurationseigenschaften`“.

Sie können die Ziele für das Archivprotokoll auch ausschließen, wenn Sie ein Backup von der SnapManager-CLI erstellen. Weitere Informationen finden Sie im Thema „`Datenbanksicherungen erstellen`“.

Sie können die Ziele für das Archivprotokoll auch ausschließen, wenn Sie ein Backup von der SnapManager-GUI erstellen.



 a| 
Haben Sie eine FlexClone Lizenz, wenn Sie SnapManager mit NFS Datenbanken verwenden?
 a| 
Zur Nutzung aller Vorteile von SnapManager mit NFS-Datenbanken ist eine FlexClone Lizenz erforderlich. SnapManager erledigt diese Aufgaben mit der FlexClone Funktion:

* Backups von NFS-Datenbanken mounten
* Backup von NFS-Datenbanken überprüfen
* Klonen von NFS-Datenbanken
* Registrieren von Backups der NFS-Datenbanken mit RMAN (bei Verwendung von RMAN)




 a| 
Konnte keine Verbindung zum Repository hergestellt werden?
 a| 
Wenn die Verbindung zu einem Repository fehlschlägt, führen Sie den Befehl lsnrctl Status in der Repository-Datenbank aus, und überprüfen Sie die aktiven Dienstnamen. Wenn SnapManager eine Verbindung zur Repository-Datenbank herstellt, wird der Servicename der Datenbank verwendet. Je nach Einrichtung des Listeners kann dies der kurze Servicename oder der vollqualifizierte Servicename sein. Wenn SnapManager eine Verbindung zu einer Datenbank für einen Backup-, Restore- oder anderen Vorgang herstellt, verwendet er den Host-Namen und den SID. Wenn das Repository nicht korrekt initialisiert wird, weil es derzeit nicht erreichbar ist, erhalten Sie eine Fehlermeldung, in der Sie gefragt werden, ob Sie das Repository entfernen möchten. Sie können das Repository aus Ihrer aktuellen Ansicht entfernen, sodass Sie Vorgänge für andere Repositories ausführen können.

Prüfen Sie außerdem, ob die Repository-Instanz ausgeführt wird, indem Sie das ps -eaf ausführen



| Grepinstance - Name Befehl.  a| 
Kann das System den Hostnamen auflösen?



 a| 
Überprüfen Sie, ob sich der angegebene Hostname in einem anderen Subnetz befindet. Wenn Sie eine Fehlermeldung erhalten, dass SnapManager den Hostnamen nicht auflösen kann, fügen Sie den Hostnamen in die Hostdatei hinzu.Fügen Sie den Hostnamen zur Datei unter /etc/Hosts hinzu: Xxx.xxx.xxx.xxx.xxx Hostname IP-Adresse
 a| 
Führt SnapDrive aus?



 a| 
Überprüfen Sie, ob der SnapDrive Daemon ausgeführt wird: -Snapdrived Status

Wenn der Daemon nicht ausgeführt wird, wird eine Meldung angezeigt, die angibt, dass ein Verbindungsfehler vorliegt.
 a| 
Welche Storage-Systeme sind für den Zugriff mit SnapDrive konfiguriert?



 a| 
Führen Sie den Befehl: -SnapDrive config list aus
 a| 
Wie kann die SnapManager GUI Performance verbessert werden?



 a| 
* Stellen Sie sicher, dass Sie über gültige Benutzeranmeldeinformationen für das Repository, den Profilhost und das Profil verfügen.
+
Wenn Ihre Anmeldedaten ungültig sind, löschen Sie die Benutzeranmeldeinformationen für das Repository, den Profilhost und das Profil. Setzen Sie dieselben Benutzeranmeldeinformationen zurück, die Sie zuvor für das Repository, den Profilhost und das Profil festgelegt haben. Weitere Informationen zum erneuten Einstellen der Benutzeranmeldeinformationen finden Sie unter „`SFestlegen von Anmeldeinformationen nach Löschen des Anmeldeinformationscache`“.

* Schließen Sie die nicht verwendeten Profile.
+
Wenn mehr Profile geöffnet werden, wird die Performance der SnapManager GUI beeinträchtigt.

* Überprüfen Sie, ob Sie *beim Start öffnen* im Fenster Benutzereinstellungen im Menü *Admin* in der SnapManager-Benutzeroberfläche aktiviert haben.
+
Wenn diese Option aktiviert ist, wird die unter /root/.netapp/smo/3.3.0/gui/State verfügbare Benutzerkonfigurationsdatei (user.config) als openOnStartup=PROFIL angezeigt.

+
Da *Öffnen auf Start* aktiviert ist, müssen Sie nach kürzlich geöffneten Profilen aus der SnapManager-Benutzeroberfläche suchen, wobei lastOpenProfiles in der Benutzerkonfiguration (user.config)-Datei verwendet werden: LASTOPENPROFILE1,PROFILE2,PROFIL3,...

+
Sie können die aufgeführten Profilnamen löschen und immer eine minimale Anzahl von Profilen als offen halten.

* Das geschützte Profil benötigt mehr Zeit zur Aktualisierung als das nicht geschützte Profil.
+
Das geschützte Profil wird in einem Zeitintervall aktualisiert, basierend auf dem im protectionStatusRefresRate Parameter der Benutzerkonfigurationsdatei (user.config) angegebenen Wert.

+
Sie können den Wert aus dem Standardwert (300 Sekunden) erhöhen, sodass die geschützten Profile erst nach dem festgelegten Zeitintervall aktualisiert werden.

* Löschen Sie vor der Installation der neuen SnapManager-Version in der UNIX-basierten Umgebung die clientseitigen Einträge von SnapManager, die an folgender Stelle verfügbar sind:
+
/Root/.netapp


 a| 
Wenn mehrere SnapManager Vorgänge gestartet und gleichzeitig im Hintergrund ausgeführt werden, benötigt die SnapManager GUI mehr Zeit für die Aktualisierung. Wenn Sie mit der rechten Maustaste auf das Backup klicken (das bereits gelöscht ist, aber immer noch in der SnapManager GUI angezeigt wird), sind die Backup-Optionen für dieses Backup nicht im Fenster Backup oder Clone aktiviert.



 a| 
Sie müssen warten, bis die SnapManager GUI aktualisiert wird, und dann den Backup-Status überprüfen.
 a| 
Was würden Sie tun, wenn die Oracle-Datenbank nicht auf Englisch eingestellt ist?



 a| 
SnapManager-Vorgänge können fehlschlagen, wenn die Sprache für eine Oracle-Datenbank nicht auf Englisch festgelegt ist. Legen Sie die Sprache der Oracle-Datenbank auf Englisch fest:

. Fügen Sie unter den ersten Kommentaren in /etc/init.d/smo_Server Folgendes hinzu
+
** NLS_LANG=American_America
** NLS_LANG exportieren


. Starten Sie den SnapManager-Server mit dem folgenden Befehl neu: smo_Server restart



NOTE: Wenn die Anmeldeskripte wie .bash_profile, .bashrc und .cschric für den Oracle-Benutzer auf NLS_LANG gesetzt sind, müssen Sie das Skript bearbeiten, um NLS_LANG nicht zu überschreiben.
 a| 
Was würden Sie tun, wenn die Backup-Planung fehlschlägt, wenn die Repository-Datenbank auf mehr als eine IP verweist und jede IP einen anderen Hostnamen hat?



 a| 
. Beenden Sie den SnapManager-Server.
. Löschen Sie die Zeitplandateien im Repository-Verzeichnis von den Hosts, auf denen Sie den Backup-Zeitplan auslösen möchten.
+
Die Namen der Zeitplandateien können in den folgenden Formaten vorliegen:

+
** Repository#repo_username#Repository_Database_Name#Repository_Host#repo_Port
** Repository-repo_usernamerepository_Database_Name-Repository_Host-repo_Port *Hinweis:* Sie müssen sicherstellen, dass Sie die Terminplandatei in dem Format löschen, das den Details des Projektarchivs entspricht.


. Starten Sie den SnapManager-Server neu.
. Öffnen Sie andere Profile unter dem gleichen Repository von der SnapManager GUI, um sicherzustellen, dass keine Terminplaninformationen dieser Profile fehlen.

 a| 
Was würden Sie tun, wenn der SnapManager-Vorgang mit dem Fehler der Dateisperre für Zugangsdaten fehlschlägt?



 a| 
SnapManager sperrt die Anmeldeinformationsdatei vor dem Aktualisieren und entsperrt sie nach dem Aktualisieren.Wenn mehrere Operationen gleichzeitig ausgeführt werden, kann einer der Operationen die Anmeldeinformationsdatei sperren, um sie zu aktualisieren. Wenn ein anderer Vorgang versucht, gleichzeitig auf die Datei mit gesperrten Anmeldeinformationen zuzugreifen, schlägt der Vorgang mit dem Dateisperrfehler fehl.

Konfigurieren Sie in der Datei smo.config die folgenden Parameter, je nach Häufigkeit der gleichzeitigen Operationen:

* FileLock.retryIntervall = 100 Millisekunden
* FileLock.Timeout = 5000 Millisekunden



NOTE: Die den Parametern zugewiesenen Werte müssen in Millisekunden liegen.
 a| 
Was würden Sie tun, wenn der Zwischenstatus des Backup Verify-Vorgangs auf der Registerkarte Monitor fehlgeschlagen angezeigt wird, obwohl der Backup Verify-Vorgang noch ausgeführt wird?



 a| 
Die Fehlermeldung wird in der Datei sm_gui.log protokolliert. Sie müssen in der Protokolldatei nachsehen, um die neuen Werte für den Vorgang zu bestimmen.heartbeatIntervall und Operation.heartbeatThreshold Parameter, die dieses Problem lösen werden.

. Fügen Sie die folgenden Parameter in der Datei smo.config hinzu:
+
** Operation.heartbeatIntervall = 5000
** Operation.heartbeatThreshold = 5000 der von SnapManager zugewiesene Standardwert ist 5000.


. Diesen Parametern die neuen Werte zuweisen.
+

NOTE: Die den Parametern zugewiesenen Werte müssen in Millisekunden liegen.

. Starten Sie den SnapManager-Server neu, und führen Sie den Vorgang erneut aus.

 a| 
Was ist zu tun, wenn ein Heap-Space-Problem auftritt?



 a| 
Wenn während des SnapManager für Oracle-Betriebs ein Heap-Space-Problem auftritt, müssen Sie die folgenden Schritte durchführen:

. Wechseln Sie zum Installationsverzeichnis für SnapManager für Oracle.
. Öffnen Sie die Datei launchjava aus dem Installationsverzeichnis/bin/launchjava-Pfad.
. Erhöhen Sie den Wert des Java -Xmx160m Java Heap-space Parameters.
+
So können Sie beispielsweise den Standardwert von 160 m auf 200 m erhöhen.

+

NOTE: Wenn Sie den Wert des Java Heap-space-Parameters in den früheren Versionen von SnapManager für Oracle erhöht haben, sollten Sie diesen Wert beibehalten.


 a| 
Was würden Sie tun, wenn Sie die geschützten Backups nicht zum Wiederherstellen oder Klonen verwenden können?



 a| 
Dieses Problem wird beobachtet, wenn Sie SnapManager 3.3.1 mit Clustered Data ONTAP verwendet haben und ein Upgrade auf SnapManager 3.4 durchgeführt haben. Die Backups wurden mithilfe von Post-Skripten in SnapManager 3.3 gesichert. Ab SnapManager 3.4 sind die Backups entweder über _SnapManager_cDOT_Mirror_ oder _SnapManager_cDOT_Vault_ Richtlinien gesichert, die beim Erstellen eines Profils ausgewählt werden. Nach einem Upgrade auf SnapManager 3.4 können Sie eventuell noch die alten Profile nutzen und so Backups mit Backup-Skripten schützen. Sie können sie aber nicht zur Wiederherstellung oder zum Klonen mit SnapManager verwenden.

Sie müssen das Profil aktualisieren und entweder die Richtlinie _SnapManager_cDOT_Mirror_ oder _SnapManager_cDOT_Vault_ auswählen und das Post-Skript, das zur Datensicherung in SnapManager 3.3 verwendet wurde, löschen.
 a| 
Was würden Sie tun, wenn geplante Backups nicht gesichert werden (SnapVault)?

|===