---
permalink: unix-administration/reference_the_smosmsapclone_template_command.html 
sidebar: sidebar 
keywords: command, create, clone, specification, template, smo 
summary: Mit diesem Befehl können Sie eine Vorlage für die Klonspezifikation erstellen. 
---
= Der Befehl smo Clone template
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit diesem Befehl können Sie eine Vorlage für die Klonspezifikation erstellen.



== Syntax

[listing]
----

        smo clone template
-profile name
\[-backup-id guid  \| -backup-label backup_name\]
\[-quiet \| -verbose\]
----


== Parameter

* *-Profilname*
+
Gibt die Datenbank an, für die Sie eine Klonspezifikation von erstellen möchten. Das Profil enthält die Kennung der Datenbank und andere Datenbankinformationen.

* *-Backup-id Guid*
+
Erstellt eine Klonspezifikation aus der Sicherung mit der angegebenen GUID. Die GUID wird von SnapManager beim Erstellen eines Backups generiert. Verwenden Sie den Befehl smo Backup list, um die GUID für jedes Backup anzuzeigen.

* *-Backup-Label Backup_Label_Name*
+
Erstellt eine Klonspezifikation aus der Sicherung mit dem angegebenen Backup-Label.

* *-ruhig*
+
Zeigt nur Fehlermeldungen auf der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen an der Konsole an.





== Beispielbefehl

Im folgenden Beispiel wird aus dem Backup eine Klon-Spezifikations-Vorlage mit dem Label full_Backup_Sales_May erstellt. Sobald der Befehl smo Clone Template abgeschlossen ist, ist die Klon-Spezifikations-Vorlage abgeschlossen.

[listing]
----
smo clone template -profile SALES1 -backup-label full_backup_sales_May
Operation Id [8abc01ec0e79004b010e79006da60001] succeeded.
----
*Verwandte Informationen*

xref:task_creating_clone_specifications.adoc[Erstellen von Klonspezifikationen]

xref:task_cloning_databases_from_backups.adoc[Klonen von Datenbanken aus Backups]
