---
permalink: unix-administration/reference_the_smosmsap_notification_updatesummarynotification_command.html 
sidebar: sidebar 
keywords: run, notification, update-summary-notification, command, summary, enable, repository, database, smo 
summary: Sie können den Befehl Notification Update-summary-notification ausführen, um eine zusammenfassende Benachrichtigung für eine Repository-Datenbank zu aktivieren. 
---
= Der Befehl smo notification Update-summary-notification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Befehl Notification Update-summary-notification ausführen, um eine zusammenfassende Benachrichtigung für eine Repository-Datenbank zu aktivieren.



== Syntax

[listing]
----

        smo notification update-summary-notification
-repository
-port repo_port
-dbname  repo_service_name
-host repo_host
-login -username repo_username
-email email-address1,email-address2
-subject subject-pattern
-frequency
[-daily –time daily_time \|
-hourly –time hourly_time \|
-monthly –time monthly_time -date \[1\|2\|3\|...\|31\] \|
-weekly  –time weekly_time -day \[1\|2\|3\|4\|5\|6\|7\]\]
-profiles profile1,profile2
-notification-host notification-host
\[-quiet \| -verbose\]
----


== Parameter

* *-Repository*
+
Gibt die Details der Repository-Datenbank an.

* *-Port repo_Port*
+
Gibt die TCP-Portnummer an, die für den Zugriff auf die Repository-Datenbank verwendet wird.

* *-dbname repo_Service_Name*
+
Gibt den Namen der Repository-Datenbank an. Sie können entweder den globalen Namen oder die Systemkennung verwenden.

* *-Host repo_Host*
+
Gibt den Namen oder die IP-Adresse des Hosts an, auf dem sich die Repository-Datenbank befindet.

* *-Login*
+
Gibt die Anmeldedaten für das Repository an. Dies ist optional. Wenn nicht angegeben, verwendet SnapManager standardmäßig den Verbindungsmodus für OS-Authentifizierung.

* *-username repo_username*
+
Gibt den Benutzernamen an, der für den Zugriff auf die Repository-Datenbank erforderlich ist.

* *-Email-Adresse1, E-Mail-Adresse2*
+
Gibt E-Mail-Adressen der Empfänger an.

* *-Betreff-Muster*
+
Gibt das Muster für E-Mail-Betreff an.

* *-Frequenz { -täglich --Zeit Tageszeit - stündlich --Zeit Stundenweise --Zeit monatlich --Zeit monatlich_Zeit -Datum {1 natürlich 3... 31 } --Zeit wöchentlich - Zeit wöchentlich - Tag {1 2 3 4 5 natürlich 6 7 } }*
+
Gibt den Terminplantyp und die Zeitplandauer an, wann die E-Mail-Benachrichtigung angezeigt werden soll.

* *-Profile profil1, profil2*
+
Gibt Profilnamen an, die E-Mail-Benachrichtigungen erfordern.

* *-notification-Host notification-Host*
+
Gibt den SnapManager-Server-Host an, von dem aus die Zusammenfassung Benachrichtigungs-E-Mail an die Empfänger gesendet wird. Sie können Hostnamen oder IP-Adressen für den Benachrichtigungs-Host angeben. Sie können auch die Host-IP oder den Host-Namen aktualisieren.

* *-ruhig*
+
Zeigt nur Fehlermeldungen in der Konsole an. Standardmäßig werden Fehler- und Warnmeldungen angezeigt.

* *-verbose*
+
Zeigt Fehler-, Warn- und Informationsmeldungen in der Konsole an.





== Beispiel

Das folgende Beispiel ermöglicht eine zusammenfassende Benachrichtigung für eine Repository-Datenbank:

[listing]
----

smo notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1
----