---
permalink: unix-administration/task_changing_the_retention_policy_default_behavior.html 
sidebar: sidebar 
keywords: backup, expire, based, retention, policy, snapmanager, determine, delete, backup, setting, policy, default, behavior 
summary: Wenn ein Backup basierend auf der Aufbewahrungsrichtlinie abläuft, bestimmt SnapManager basierend auf den Aufbewahrungseinstellungen, ob das Backup gelöscht werden soll. Das Löschen von Backups ist das Standardverhalten. Sie können dieses Standardverhalten ändern und stattdessen die ungeschützten Backups freigeben. 
---
= Ändern des Standardverhaltens der Aufbewahrungsrichtlinie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn ein Backup basierend auf der Aufbewahrungsrichtlinie abläuft, bestimmt SnapManager basierend auf den Aufbewahrungseinstellungen, ob das Backup gelöscht werden soll. Das Löschen von Backups ist das Standardverhalten. Sie können dieses Standardverhalten ändern und stattdessen die ungeschützten Backups freigeben.

Standardmäßig löscht SnapManager Backups, je nachdem, ob sie wie folgt geschützt sind oder nicht:

* Für geschützte Backups entlastet SnapManager die lokalen Backups, sobald diese ablaufen.
* Bei ungesicherten Backups löscht SnapManager die lokalen Backups nach ihrem Ablauf.
+
Sie können dieses Standardverhalten ändern.



Bei geschützten Backups berücksichtigt SnapManager nicht die folgenden Kriterien bei der Bestimmung, ob die lokale Kopie gelöscht werden soll:

* Das Backup auf den sekundären Storage ist ausgefallen oder wird gerade geschützt.
+
Dies ermöglicht die Übertragung von Backups auf den Sekundärspeicher, bevor die Aufbewahrungsrichtlinie angewendet wird.

* Die Kopie wurde anschließend aus dem Sekundärspeicher gelöscht.
+
.. Zugriff auf den folgenden Standardspeicherort:
+
Standard smo Installationsort/Properties/smo.config

.. Bearbeiten Sie die Datei smo.config.
.. Legen Sie in der Datei smo.config die Eigenschaft contee.alwayFreeExpiredBackups auf true fest.
+
Beispiel: „Exkepe.alwayFreeExpiredBackups“ = „true“





*Verwandte Informationen*

xref:reference_the_smosmsapbackup_update_command.adoc[Der SMO-Befehl zum Aktualisieren der Datensicherung]
