---
permalink: unix-administration/task_issuing_commands_from_an_alternate_host.html 
sidebar: sidebar 
keywords: issue, cli, command, host, database, snapmanager, route, appropriate, alternate 
summary: Sie können CLI-Befehle von einem anderen Host als dem Datenbank-Host ausführen, und SnapManager führt die Befehle durch, die Sie an den entsprechenden Host eingeben. 
---
= Befehle von einem alternativen Host ausgeben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können CLI-Befehle von einem anderen Host als dem Datenbank-Host ausführen, und SnapManager führt die Befehle durch, die Sie an den entsprechenden Host eingeben.

Damit das System einen Vorgang an den richtigen Host sendet, muss es zunächst wissen, wo das Profil für den Vorgang gefunden werden soll. In diesem Verfahren speichert das System das Profil in Repository-Zuordnungsinformationen für eine Datei im Home-Verzeichnis des Benutzers auf dem lokalen Host.

. Um das Home-Verzeichnis des lokalen Benutzers auf die Profile-zu-Repository-Zuordnungen aufmerksam zu machen, damit die Anforderung der Operation weiterleiten kann, geben Sie den folgenden Befehl ein:
`smo profile sync -repository-dbname repo_dbname-host repo_host-port repo_port-login-username repo_username [-quiet | -verbose]`

