---
permalink: unix-administration/task_mounting_backups.html 
sidebar: sidebar 
keywords: snapmanager, automatic, handle, mount, backup, available, host, scenario, rman, 7-mode 
summary: 'SnapManager übernimmt automatisch das Mounten eines Backups, um es dem Host zur Verfügung zu stellen. Sie können Backups auch in Szenarien einbinden, in denen Sie ein externes Tool wie Oracle Recovery Manager \(RMAN\) für den Zugriff auf die Dateien im Backup verwenden.' 
---
= Montage von Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager übernimmt automatisch das Mounten eines Backups, um es dem Host zur Verfügung zu stellen. Sie können Backups auch in Szenarien einbinden, in denen Sie ein externes Tool wie Oracle Recovery Manager (RMAN) für den Zugriff auf die Dateien im Backup verwenden.

Wenn Sie RMAN verwenden, müssen Sie den Mount-Vorgang verwenden, um den Status eines Backups zu ändern (wodurch der Zugriff möglich ist) und den Unmount-Vorgang, um den Status eines Backups zu ändern (wodurch der Zugriff entfernt wird).

Der Befehl smo Backup Mount zeigt eine Liste von Pfaden an, wo die Snapshot Kopien, die aus dem Backup bestehen, gemountet wurden.

Sie können die Option -from-secondary verwenden, um das Backup aus dem sekundären Speicher zu mounten. Wenn Sie diese Option nicht verwenden, hängt SnapManager das Backup vom primären Storage ab.

Sie müssen die Option -copy-id angeben, wenn Sie die Option -from-secondary angeben. Wenn auf dem sekundären Speichersystem mehrere Backups vorhanden sind, wird mit der Option -copy-id angegeben, welche Sicherungskopie auf dem sekundären Speicher zum Mounten des Backups verwendet werden soll.6


NOTE: Wenn Sie Data ONTAP in 7-Mode verwenden, müssen Sie einen gültigen Wert für die Option -copy-id angeben. Wenn Sie jedoch Clustered Data ONTAP verwenden, ist die Option -copy-id nicht erforderlich.

Wenn Sie ein Datenbank-Backup auf einen Remote-Host mounten, müssen Sie sicherstellen, dass die ASM-Anmeldedaten auf beiden Hosts dieselben sind.


NOTE: Optional können Sie die Dump-Dateien nach einem erfolgreichen oder fehlgeschlagenen Backup-Mount-Vorgang sammeln.

. Geben Sie zum Mounten eines Backups den folgenden Befehl ein:
`smo backup mount -profile profile_name {labellabel [data | -archivelogs] | -idid} [-host-host] [-from-secondary [-copy-id id]] [-dump] [-quiet | -verbose]`


*Verwandte Informationen*

xref:reference_the_smosmsapbackup_mount_command.adoc[Der Befehl smo Backup Mount]
