---
permalink: unix-administration/task_using_snapmanager_for_oracle_to_create_the_database_profile_and_assign_a_protection_policy.html 
sidebar: sidebar 
keywords: create, profile, snapmanager, oracle, enable, protect, client, payroll, paydb 
summary: Sie müssen in SnapManager für Oracle ein Profil erstellen, den Schutz im Profil aktivieren und eine Sicherungsrichtlinie zuweisen, um ein geschütztes Backup zu erstellen. 
---
= Verwenden von SnapManager für Oracle, um das Datenbankprofil zu erstellen und eine Sicherungsrichtlinie zuzuweisen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen in SnapManager für Oracle ein Profil erstellen, den Schutz im Profil aktivieren und eine Sicherungsrichtlinie zuweisen, um ein geschütztes Backup zu erstellen.

Ein Profil enthält Informationen über die zu verwaltende Datenbank, einschließlich der Anmeldeinformationen, Backup-Einstellungen und Sicherungseinstellungen für Backups. Nachdem Sie ein Profil erstellt haben, müssen Sie bei jedem Vorgang keine Datenbankdetails angeben. Ein Profil kann nur auf eine Datenbank verweisen, auf die dieselbe Datenbank kann jedoch mehrere Profile verweisen.

. Wechseln Sie zum SnapManager für Oracle Client.
. Klicken Sie in der Verzeichnisstruktur Repositories mit der rechten Maustaste auf den Host, und wählen Sie *Profil erstellen*.
. Geben Sie auf der Seite Profilkonfigurationsinformationen die Profildetails ein, und klicken Sie auf *Weiter*.
+
Sie können die folgenden Informationen eingeben:

+
** Profilname: Payroll_prod2
** Profilpasswort: Payrol123
** Kommentar: Production Payroll Datenbank


. Geben Sie auf den Seiten Datenbankkonfigurationsinformationen die Datenbankdetails ein, und klicken Sie auf *Weiter*.
+
Sie können die folgenden Informationen eingeben:

+
** Datenbankname: PAYDB
** Datenbank-SID: Payrolldb
** Datenbank-Host: Standard akzeptieren. Da Sie ein Profil von einem Host in der Repository-Struktur erstellen, zeigt SnapManager den Hostnamen an.
** Host-Konto, Vertretung des Oracle-Benutzerkontos: oracle
** Host-Gruppe, die die Oracle-Gruppe repräsentiert: dba


. Klicken Sie auf der Seite Datenbankverbindungsinformationen auf *Datenbankauthentifizierung verwenden*, um Benutzern die Authentifizierung anhand von Datenbankinformationen zu ermöglichen.
. Geben Sie die Daten zur Datenbankverbindung ein und klicken Sie auf *Weiter*.
+
Sie können die folgenden Informationen eingeben:

+
** SYSDBA Privileged User Name, der den Systemadministrator der Systemdatenbank repräsentiert, der über Administratorrechte verfügt: Sys
** Kennwort (SYSDBA-Kennwort): oracle
** Port zur Verbindung mit Datenbank-Host: 1521


. Klicken Sie auf der Seite RMAN-Konfigurationsinformationen auf *nicht RMAN verwenden* und klicken Sie auf *Weiter*.
+
Oracle Recovery Manager (RMAN) ist ein Oracle Tool für das Backup und Recovery von Oracle Datenbanken mithilfe der Erkennung auf Blockebene.

. Geben Sie auf der Seite Snapshot Naming Information eine Namenskonvention für die mit diesem Profil verknüpften Snapshots an, indem Sie Variablen auswählen.
+
Die smid-Variable erstellt eine eindeutige Snapshot-ID.

+
Führen Sie Folgendes aus:

+
.. Wählen Sie in der Liste Variable Token den Benutzertext aus und klicken Sie auf *Hinzufügen*.
.. Geben Sie payroll.techco.com_ als Host-Name ein und klicken Sie auf *OK*.
.. Klicken Sie auf *links*, bis der Hostname kurz nach dem Smo im Feld Format angezeigt wird.
.. Klicken Sie Auf *Weiter*.


+
Die Snapshot Namenskonvention von smo_hostname_smoprofile_dbsid_scope_Mode_smid wird „smo_payroll.techco.com_payroll_prod2_payrolldb_f_a_x" (wo „f“ auf ein vollständiges Backup hinweist, „A“ den automatischen Modus angibt, und „x“ stellt den einzigartigen SMID dar).

. Wählen Sie *Protection Manager Protection Policy* Aus.
+
Mit der *Protection Manager Protection Policy* können Sie eine Schutzrichtlinie auswählen, die mithilfe der NetApp Management Console konfiguriert wurde.

. Wählen Sie aus den Schutzrichtlinien der NetApp Management Console *TechCo Payroll Data: Backup* aus und klicken Sie auf *Weiter*.
. Überprüfen Sie auf der Seite Vorgang durchführen die Informationen und klicken Sie auf *Erstellen*.
. Klicken Sie auf *Operation Details*, um Informationen über den Vorgang zum Erstellen von Profilen und zur Volume-basierten Wiederherstellung anzuzeigen.
+
** Die Zuweisung einer NetApp Management Console Sicherungsrichtlinie für das Datenbankprofil erstellt automatisch einen nicht konformen Datensatz, der für den NetApp Management Console Operator sichtbar ist. Dabei wird der Name convention smo_<hostname>_<profilname> oder in diesem Beispiel: smo_payroll.tech.com_PAYDB angegeben.
** Falls das Profil nicht für die Wiederherstellung von Volumes geeignet ist (auch als „schnelle Wiederherstellung“ bezeichnet), geschieht Folgendes:
+
*** Die Registerkarte *Ergebnisse* zeigt an, dass die Profilerstellung erfolgreich war und dass während des Vorgangs Warnungen aufgetreten sind.
*** Die Registerkarte *Operation Details* enthält ein WARNPROTOKOLL, in dem angegeben wird, dass das Profil nicht für eine schnelle Wiederherstellung geeignet ist und warum.





