---
permalink: unix-administration/task_clearing_user_credentials_for_all_hosts_repositories_and_profiles.html 
sidebar: sidebar 
keywords: clear, cache, credentials, resource, host, repositories, profile, delete, smo, cli 
summary: 'Sie können den Cache Ihrer Anmeldeinformationen für Ressourcen \(Hosts, Repositorys und Profile\) löschen. Dadurch werden alle Ressourcen-Anmeldeinformationen für den Benutzer gelöscht, der den Befehl ausführt. Nach dem Löschen des Cache müssen Sie Ihre Anmeldeinformationen erneut authentifizieren, um auf diese gesicherten Ressourcen zugreifen zu können.' 
---
= Löschen von Benutzeranmeldeinformationen für alle Hosts, Repositorys und Profile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Cache Ihrer Anmeldeinformationen für Ressourcen (Hosts, Repositorys und Profile) löschen. Dadurch werden alle Ressourcen-Anmeldeinformationen für den Benutzer gelöscht, der den Befehl ausführt. Nach dem Löschen des Cache müssen Sie Ihre Anmeldeinformationen erneut authentifizieren, um auf diese gesicherten Ressourcen zugreifen zu können.

. Um Ihre Anmeldeinformationen zu löschen, geben Sie den Befehl smo cridentials clear in der SnapManager-CLI ein, oder wählen Sie in der SnapManager-Benutzeroberfläche *Admin* > *Anmeldeinformationen* > *Cache löschen* aus.
. Schließen Sie die SnapManager-Benutzeroberfläche.
+
HINWEIS:

+
** Wenn Sie den Anmeldeinformationscache von der SnapManager-GUI gelöscht haben, müssen Sie die SnapManager-Benutzeroberfläche nicht beenden.
** Wenn Sie den Anmeldeinformationscache von der SnapManager-CLI gelöscht haben, müssen Sie die SnapManager-GUI neu starten.
** Wenn Sie die verschlüsselte Anmeldedatei manuell gelöscht haben, müssen Sie die SnapManager-GUI erneut starten.


. Um die Anmeldeinformationen erneut festzulegen, wiederholen Sie den Vorgang, um die Anmeldeinformationen für das Repository, den Profilhost und das Profil festzulegen. Weitere Informationen zum erneuten Einstellen der Benutzeranmeldeinformationen finden Sie unter „Anmeldeinformationen nach dem Löschen des Anmeldeinformationscache festlegen“.


*Verwandte Informationen*

xref:reference_the_smosmsapcredential_clear_command.adoc[Der Befehl smo Credential Clear]
