---
permalink: unix-administration/task_upgrading_snapmanager_for_oracle_hosts_c1.html 
sidebar: sidebar 
keywords: upgrade, all, exist, host, latest, version, snapmanager, simultaneously, downtime, upgrading, command-line, interface, cli, smo, chmod 
summary: Sie können alle vorhandenen Hosts auf die neueste Version von SnapManager aktualisieren. Alle Hosts werden gleichzeitig aktualisiert. Dies kann jedoch zu einer Ausfallzeit aller SnapManager-Hosts und der geplanten Operationen während dieser Zeit führen. 
---
= Aktualisieren der SnapManager-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können alle vorhandenen Hosts auf die neueste Version von SnapManager aktualisieren. Alle Hosts werden gleichzeitig aktualisiert. Dies kann jedoch zu einer Ausfallzeit aller SnapManager-Hosts und der geplanten Operationen während dieser Zeit führen.

. Melden Sie sich beim Hostsystem als Root-Benutzer an.
. Navigieren Sie von der Befehlszeilenschnittstelle (CLI) zu dem Speicherort, an dem Sie die Installationsdatei heruntergeladen haben.
. Wenn die Datei nicht ausführbar ist, ändern Sie die Berechtigungen:
`chmod 544 netapp.smo*`
. Stoppen Sie den SnapManager Server:
`smo_server stop`
. Je nach UNIX Host, installieren Sie SnapManager:
+
|===
| Wenn das Betriebssystem... | Starten Sie dann... 


 a| 
*Solaris (SPARC64)*
 a| 



 a| 
*Solaris (x86_64)*
 a| 



 a| 
*AIX (PPC64)*
 a| 



 a| 
* Linux x86*
 a| 



 a| 
* Linux x64*
 a| 

|===
. Drücken Sie auf der Einführungsseite *Enter*, um fortzufahren.
+
Die folgende Meldung wird angezeigt: Vorhandene SnapManager für Oracle erkannt.

. Drücken Sie *Enter*.
. Führen Sie an der Eingabeaufforderung Folgendes aus:
+
.. Drücken Sie *Enter*, um den Standardwert für den Benutzer des Betriebssystems zu übernehmen.
.. Geben Sie den richtigen Wert für die Betriebssystemgruppe ein, oder drücken Sie *Enter*, um den Standardwert zu akzeptieren.
.. Geben Sie den richtigen Wert für den Starttyp des Servers ein, oder drücken Sie *Enter*, um den Standardwert zu akzeptieren.


+
Die Konfigurationsübersicht wird angezeigt.

. Drücken Sie *Enter*, um fortzufahren.
+
Die folgende Meldung wird angezeigt: Die Deinstallation von vorhandenem SnapManager für Oracle hat begonnen.

+
Die Deinstallation ist abgeschlossen und die aktuelle Version von SnapManager ist installiert.


