---
permalink: unix-administration/task_configuring_summary_e_mail_notification_for_multiple_profiles.html 
sidebar: sidebar 
keywords: snapmanager, enable, configure, summary, email, notification, multiple, profile, repository, database 
summary: Mit SnapManager können Sie eine E-Mail-Benachrichtigung für mehrere Profile unter einer Repository-Datenbank konfigurieren. 
---
= Konfigurieren einer E-Mail-Benachrichtigung mit Zusammenfassung für mehrere Profile
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapManager können Sie eine E-Mail-Benachrichtigung für mehrere Profile unter einer Repository-Datenbank konfigurieren.

Sie können den SnapManager-Server-Host als Benachrichtigungs-Host festlegen, von dem aus die zusammenfassende Benachrichtigung E-Mail an die Empfänger gesendet wird. Wenn der Hostname oder die IP-Adresse des SnapManager-Servers geändert wird, kann auch der Benachrichtigungs-Host aktualisiert werden.

Sie können eine der Zeitplanzeiten auswählen, zu denen Sie eine E-Mail-Benachrichtigung benötigen:

* Stündlich: Um jede Stunde eine E-Mail-Benachrichtigung zu erhalten
* Täglich: Um täglich eine E-Mail-Benachrichtigung zu erhalten
* Wöchentlich: Um wöchentlich eine E-Mail-Benachrichtigung zu erhalten
* Monatlich: Um monatlich eine E-Mail-Benachrichtigung zu erhalten


Sie müssen eine einzelne E-Mail-Adresse oder eine kommagetrennte Liste von E-Mail-Adressen eingeben, um Benachrichtigungen für Vorgänge zu erhalten, die mit diesen Profilen durchgeführt werden. Wenn Sie mehrere E-Mail-Adressen eingeben, müssen Sie sicherstellen, dass zwischen Komma und der nächsten E-Mail-Adresse kein Leerzeichen vorhanden ist.

SnapManager ermöglicht Ihnen das Hinzufügen eines benutzerdefinierten E-Mail-Betreff unter Verwendung der folgenden Variablen:

* Profilname, der für den Datenbankvorgang verwendet wird.
* Datenbankname
* SID der Datenbank
* Name des Hostservers
* Startzeit des Datenbankvorgangs im Format yyyymmdd:hh:ss
* Endzeit des Datenbankvorgangs im Format yyyyymmdd:hh:ss
* Status des Datenbankvorgangs


Wenn Sie kein angepasstes Thema hinzufügen möchten, zeigt SnapManager eine Fehlermeldung an: Missing value -subject.

. Geben Sie folgenden Befehl ein: bbs Notification Update-summary-notification -Repository-portrepo_Port-dbnamerepo_Service_Name-hotropo_Host-Login-usernamerepo_username-emailemail_address1,email_address2-subject-pattern-frequency {-Daily-timedaily-time {4 7-31 5-3 6-protagel1} {}} 1-wöchentlicher Hinweis
+
Weitere Optionen für diesen Befehl:

+
[-Force] [-noprompt]

+
[quiet | -verbose]
----

smo notification update-summary-notification –repository –port 1521 –dbname repo2 –host 10.72.197.133 –login –username oba5 –email-address admin@org.com –subject success –frequency -daily -time 19:30:45 –profiles sales1 -notification-host wales
----

