---
permalink: unix-administration/task_resetting_profile_password.html 
sidebar: sidebar 
keywords: reset, profile, password, remember, creating, snapmanager, credentials, cli, smo 
summary: Sie können das Profilkennwort zurücksetzen, wenn Sie sich nicht an das Passwort erinnern, das Sie beim Erstellen des Profils angegeben haben. 
---
= Profilkennwort wird zurückgesetzt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Profilkennwort zurücksetzen, wenn Sie sich nicht an das Passwort erinnern, das Sie beim Erstellen des Profils angegeben haben.

* Sie müssen sicherstellen, dass der SnapManager-Server auf der Repository-Datenbank ausgeführt wird.
* Sie müssen über die Anmeldedaten des Root-Benutzers für den Host verfügen, auf dem sich die Repository-Datenbank befindet.
* Sie müssen sicherstellen, dass das Profil nicht für einen Vorgang verwendet wird, wenn das Passwort für dieses Profil zurückgesetzt wird.


Sie können das Passwort entweder von der SnapManager-CLI oder von der GUI aus zurücksetzen. Beim Zurücksetzen des Passworts fragt SnapManager den SnapManager-Server auf dem Repository-Host ab, um das Betriebssystem für den Repository-Host zu identifizieren. Sie müssen die Anmeldeinformationen für den autorisierten Benutzer für die Verbindung zum Repository-Host eingeben. Der SnapManager-Server authentifiziert Benutzer mit ihren Root-Anmeldedaten auf der Repository-Datenbank. Wenn die Authentifizierung erfolgreich ist, setzt SnapManager das Profilkennwort auf dem SnapManager-Server mit dem neuen Passwort zurück.


NOTE: SnapManager führt den Verlauf der Vorgänge zum Zurücksetzen von Passwörtern nicht aus.

. Zurücksetzen des Profilpassworts durch Eingabe des folgenden Befehls: 'smo password Reset -profilprofile [-profile-passwordprofile_password] [-Repository-hostadmin-passwordadmin_password]'

