---
permalink: unix-administration/task_restoring_backups_using_fast_restore.html 
sidebar: sidebar 
keywords: force, snapmanager, oracle, volume-based, snaprestore, restore, process 
summary: Sie können SnapManager für Oracle dazu zwingen, den Volume-basierten SnapRestore-Prozess anstelle anderer Restore-Prozesse zu verwenden, wenn alle obligatorischen Bedingungen für die schnelle Wiederherstellung erfüllt werden. 
---
= Wiederherstellung von Backups mit schneller Wiederherstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapManager für Oracle dazu zwingen, den Volume-basierten SnapRestore-Prozess anstelle anderer Restore-Prozesse zu verwenden, wenn alle obligatorischen Bedingungen für die schnelle Wiederherstellung erfüllt werden.

Sie können den Befehl Backup Restore mit -fast verwenden: `backup restore -fast [require | override | fallback | off]`

Sie können die Option -fast nur verwenden, wenn Sie eine vollständige Wiederherstellung eines vollständigen Backups durchführen möchten. Die Option -fast umfasst die folgenden Parameter:

* Erforderlich: Ermöglicht die Wiederherstellung eines Volumes, wenn alle obligatorischen Bedingungen für die Wiederherstellung erfüllt sind und keine überrückbaren Prüfungen gefunden werden.
+
Wenn Sie die Option -fast angeben, jedoch keinen Parameter für -fast angeben, verwendet SnapManager als Standard den Parameter-erfordern.

* Überschreiben: Ermöglicht Ihnen, nicht obligatorische Eignungsprüfungen zu überschreiben und die Volume-basierte schnelle Wiederherstellung durchzuführen.
* Fallback: Ermöglicht es Ihnen, die Datenbank mit jeder Methode wiederherzustellen, die SnapManager bestimmt.
+
Wenn Sie nicht -fast angeben, verwendet SnapManager den Parameter -Fallback als Standard.

* Aus: Sie können die Zeit, die für die Durchführung aller Eignungsprüfungen erforderlich ist, vermeiden, um einen dateibasierten Wiederherstellungsprozess anstelle des schnellen Wiederherstellungsprozesses durchzuführen.


Wenn das Backup die obligatorischen Eignungsprüfungen nicht bestanden hat, kann die schnelle Wiederherstellung nicht erfolgreich abgeschlossen werden.

SnapManager führt ausschließlich Volume-basierte schnelle Restores in UNIX-basierten Umgebungen durch. SnapManager führt in der Windows-Umgebung keine schnellen Restores durch.

Während VBSR auf der Datensicherung der Datendatei ausgeführt wird, wenn die Datendateien und die Archivprotokolldateien im selben Volume vorhanden sind und wenn die Archivprotokolldateien nicht im aktiven Dateisystem vorhanden sind, ist die Wiederherstellung und Wiederherstellung der Datenbank erfolgreich. Die zukünftigen Archiv-Log-Snapshots werden jedoch als Teil der VBSR gelöscht, was zu einem veralteten Eintrag des Archiv-Log-Backups im Repository führt.

. Geben Sie den folgenden Befehl ein:smo Backup restore -profileprofile_Name-labellabel-complete-fast requkurz-wortrecih
+
[listing]
----
smo backup restore -profile targetdb1_prof1
      -label full_bkup_sales_nov_08  -complete -fast require -verbose
----
. Prüfen Sie die Prüfungen der Berechtigung zur schnellen Wiederherstellung.
. Wenn die Eignungsprüfung feststellt, dass keine obligatorischen Prüfungen fehlgeschlagen sind, wenn bestimmte Bedingungen überschrieben werden können und wenn Sie mit dem Wiederherstellungsprozess fortfahren möchten, geben Sie den folgenden Befehl ein: Backup restore -fast override


*Verwandte Informationen*

xref:task_creating_pretask_post_task_and_policy_scripts.adoc[Erstellen von vor-, Post-Task- und Richtlinienskripten]

xref:concept_variables_available_in_custom_script_for_restore_operation.adoc[Variablen, die in den Taskskripten für den Wiederherstellungsvorgang verfügbar sind]

xref:task_storing_the_task_scripts.adoc[Speichern der Taskskripte]
