---
permalink: unix-administration/task_configuring_e_mail_notification_for_an_existing_profile.html 
sidebar: sidebar 
keywords: updating, profile, configure, receive, email, notification, completion, database, operation, exist, comma-seperated, list 
summary: Wenn Sie ein Profil aktualisieren, können Sie so konfigurieren, dass Sie eine E-Mail-Benachrichtigung über den Abschluss des Datenbankvorgangs erhalten. 
---
= Konfigurieren der E-Mail-Benachrichtigung für ein vorhandenes Profil
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein Profil aktualisieren, können Sie so konfigurieren, dass Sie eine E-Mail-Benachrichtigung über den Abschluss des Datenbankvorgangs erhalten.

* Sie müssen die E-Mail-Adresse konfigurieren, von der die Meldungen gesendet werden.
* Sie müssen eine einzelne E-Mail-Adresse oder mehrere E-Mail-Adressen eingeben, an die Benachrichtigungen gesendet werden.
+
Sie können eine kommagetrennte Liste für mehrere Adressen verwenden. Sie müssen sicherstellen, dass zwischen Komma und der nächsten E-Mail-Adresse kein Leerzeichen vorhanden ist. Optional können Sie auch einen Betreff zu der E-Mail hinzufügen.

+
.. Geben Sie den folgenden Befehl ein:smo-Profil-Update -profilprofil [-profile-passwordprofile_password][-Database-dbnamedb_dbname-Host db_Host [-siddb_sid] [-Login -usernamedb_username-adressyword-contail [-{] [-commentail] [-bosrimsrims2] [-commentail] [-] [-] [-] [-]]] [-assogmemassail] [-] [-{ commentail] [-{] [-] [-] [-]]] [-bosrimprotosrimnmaimnmailgms2}}}] [-] [-] [-] [-] [-] [-] [-] [-] [-] [-commentail] [-] [-]] [-]] [-] [-] [-]]] [-]]]] [-commentail-]] [-] [-]
+
Mit der Option Erfolg erhalten Sie nur eine Benachrichtigung für erfolgreiche Datenbankvorgänge und die Ausfalloption, eine Benachrichtigung nur für fehlerhafte Datenbankvorgänge zu erhalten.




