---
permalink: unix-administration/task_adding_new_profile_to_summary_notification.html 
sidebar: sidebar 
keywords: configure, summary, email, notification, repository, database, add, new, profile 
summary: Nachdem Sie eine E-Mail-Benachrichtigung für die Repository-Datenbank konfiguriert haben, können Sie mithilfe des Befehls Summary Notification ein neues Profil zur zusammenfassenden Benachrichtigung hinzufügen. 
---
= Hinzufügen eines neuen Profils zu E-Mail-Benachrichtigungen mit Zusammenfassung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie eine E-Mail-Benachrichtigung für die Repository-Datenbank konfiguriert haben, können Sie mithilfe des Befehls Summary Notification ein neues Profil zur zusammenfassenden Benachrichtigung hinzufügen.

. Geben Sie den folgenden Befehl ein: smo-Profil create -profileprofile_Name [-profile-passwordprofile_password] -Repository-dbnamerepo_Service_Name-hostrepo_Host-portrepo_Port-Login-usernamerepo_username_countngmprop [-commosdbnum] [-admosmany-contactngname] [-assogmgn] [-composdn.jmgmgmgmgmgmgmgmgmgmgmgm-lep.jmgmgmgmgm.jm] [-{] [-budn.jmgmgmgmgmgmgmgmgmgmgmsdn.jmgmgmgmgmgmgmgmgmgmgmgm-data] [-{] [-butt.jmgmgmgmgmgmgmgm-data] [-} }-
+
Weitere Optionen für diesen Befehl:

+
[-Force]


