---
permalink: unix-administration/task_cloning_protected_backups.html 
sidebar: sidebar 
keywords: snapmanager, clone, copy, backup, protect, cloning, san, nas, ontap, 7-mode 
summary: Sie können SnapManager verwenden, um eine Kopie eines geschützten Backups zu klonen. 
---
= Klonen geschützter Backups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können SnapManager verwenden, um eine Kopie eines geschützten Backups zu klonen.

Der Host (für den Klon ausgewählt) muss über dasselbe Storage-Protokoll (z. B. SAN oder NAS) Zugriff auf den sekundären Storage haben.

Sie können mit der Option -from-secondary angeben, dass Sie aus dem sekundären Storage klonen möchten.

Sie müssen die Option -copy-id angeben, wenn Sie die Option -from-secondary angeben. Wenn auf dem sekundären Speichersystem mehrere Backups vorhanden sind, wird mit der Option -copy-id angegeben, welche Backup-Kopie auf dem sekundären Speicher zum Klonen verwendet werden soll.


NOTE: Wenn Sie Data ONTAP in 7-Mode verwenden, müssen Sie einen gültigen Wert für die Option -copy-id angeben. Wenn Sie jedoch Clustered Data ONTAP verwenden, ist die -copy-idOption nicht erforderlich.

Das Löschen der Klone geschützter Backups auf sekundären Storage-Systemen kann fehlschlagen. Dieses Problem tritt auf, wenn die Systemzeit des primären und sekundären Storage-Systems nicht synchronisiert wird.

. Erstellen Sie einen Klon einer geschützten Backup-Kopie: smo Clone create -Backup-labelBackup_Name-newsidNew_sid-labelclone_Label-profilprofile_Name-clonespepfull_path_to_clonespepfile-from-secondary -copy-idid




== Beispiel

[listing]
----
smo clone create -label testdb_clone_clstest
-profile sys_db_finance -from-secondary -copy-id 3042 sys_db_finance_sept_08
----