---
permalink: unix-administration/task_configuring_mail_server_for_a_repository.html 
sidebar: sidebar 
keywords: snapmanager, enable, specify, mail, server, detail, alert, repository, ip, address, email, server, smo, notification, set 
summary: Mit SnapManager können Sie die E-Mail-Serverdetails angeben, von denen die E-Mail-Warnungen gesendet werden. 
---
= Konfigurieren eines E-Mail-Servers für ein Repository
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit SnapManager können Sie die E-Mail-Serverdetails angeben, von denen die E-Mail-Warnungen gesendet werden.

Mit SnapManager können Sie den Hostnamen oder die IP-Adresse des Absenders sowie die Portnummer des E-Mail-Servers für einen Repository-Datenbanknamen angeben, der eine E-Mail-Benachrichtigung erfordert. Sie können die Portnummer des Mail-Servers in einem Bereich von 0 bis 65535 konfigurieren; der Standardwert ist 25. Wenn Sie eine Authentifizierung für die E-Mail-Adresse benötigen, können Sie den Benutzernamen und das Kennwort angeben.

Sie müssen den Namen oder die IP-Adresse des Hostservers angeben, der die E-Mail-Benachrichtigung verarbeitet.

. Um den E-Mail-Server zum Senden von E-Mail-Warnungen zu konfigurieren, geben Sie folgenden Befehl ein: bbs Notification Set -Sender-emailemail_address-mailhostmailhost-mailportmaiport [-Authentication-usernameusername-passwordpassword] -Repository-portrepo_Port-dbnamerepo_Service_Name-hostrepo_Host-Login-usernamernamerepo_username
+
Weitere Optionen für diesen Befehl:

+
[-Force]

+
|===
| Gehen Sie wie folgt vor: | Dann... 


 a| 
*Um die E-Mail-Adresse des Absenders anzugeben.*
 a| 
Geben Sie die Option -Sender-E-Mail an. Unter SnapManager 3.2 für Oracle können Sie Bindestrich (-) einfügen, während Sie den Domain-Namen der E-Mail-Adresse angeben. Sie können beispielsweise die Absender-E-Mail-Adresse als -sender-emailuser@org-corp.com angeben.



 a| 
*Um den E-Mail-Server-Hostnamen oder die IP-Adresse des Absenders anzugeben.*
 a| 
Geben Sie die Option -mailhost an.



 a| 
*Zur Angabe der Port-Nummer des E-Mail-Servers für einen Repository-Datenbanknamen, der eine E-Mail-Benachrichtigung erfordert. Sie können die Portnummer des Mail-Servers in einem Bereich von null bis 65535 konfigurieren; der Standardwert ist 25.*
 a| 
Geben Sie die Option -mailport an.



 a| 
*Geben Sie den Benutzernamen und das Passwort an, wenn Sie eine Authentifizierung für die E-Mail-Adresse benötigen.*
 a| 
Geben Sie die Option -Authentication an, gefolgt vom Benutzernamen und Passwort.

|===


Im folgenden Beispiel wird der Mail-Server konfiguriert.

[listing]
----
smo notification set -sender-email admin1@org.com -mailhost hostname.org.com -mailport 25 authentication -username admin1 -password admin1 -repository -port 1521 -dbname SMOREPO -host hotspur -login -username grabal21 -verbose
----