---
permalink: unix-administration/task_using_protection_manager_to_configure_a_secondary_backup_protection_policy.html 
sidebar: sidebar 
keywords: configuring, backup, schedule, storage, administrator, configure, protect 
summary: Nach der Konfiguration des Backup-Zeitplans konfiguriert der Storage-Administrator eine geschützte Backup-Storage-Richtlinie, in die dieser Zeitplan aufgenommen werden soll. 
---
= Konfigurieren einer sekundären Backup-Sicherungsrichtlinie mit Protection Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der Konfiguration des Backup-Zeitplans konfiguriert der Storage-Administrator eine geschützte Backup-Storage-Richtlinie, in die dieser Zeitplan aufgenommen werden soll.

Vor der Konfiguration der Schutzrichtlinie gibt der Storage-Administrator folgende Informationen an den DBA-Partner:

* Aufbewahrungsdauer zur Angabe für sekundären Storage
* Typ des erforderlichen sekundären Storage-Schutzes


Die Sicherungsrichtlinie, die erstellt wird, kann vom DBA-Partner in SnapManager für Oracle aufgelistet und einem Datenbankprofil für die zu sichernden Daten zugewiesen werden.

. Gehen Sie zur NetApp Management Console des Protection Manager.
. Klicken Sie in der Menüleiste auf *Richtlinien* > *Schutz* > *Übersicht*.
+
Die Registerkarte Übersicht im Fenster Schutzrichtlinien wird angezeigt.

. Klicken Sie auf *Richtlinie hinzufügen*, um den Assistenten zum Hinzufügen von Schutzrichtlinien zu starten.
. Führen Sie den Assistenten mit den folgenden Schritten aus:
+
.. Geben Sie einen beschreibenden Richtliniennamen an.
+
Geben Sie in diesem Beispiel *TechCo Payroll Data: Backup* und eine Beschreibung ein und klicken Sie dann auf *Next*.

.. Wählen Sie eine Basisrichtlinie aus.
+
Wählen Sie für dieses Beispiel *Sichern* aus und klicken Sie auf *Weiter*.

.. Akzeptieren Sie im Eigenschaftenblatt Richtlinie für den primären Datenknoten die Standardeinstellungen und klicken Sie auf *Weiter*.
+

NOTE: In diesem Beispiel wird der in SnapManager konfigurierte lokale Backup-Zeitplan angewendet. Jeder lokale Backup-Zeitplan, der mit dieser Methode angegeben wird, wird ignoriert.

.. Wählen Sie im Eigenschaftenblatt primäre Daten zu Sicherungsverbindung einen Backup-Zeitplan aus.
+
Wählen Sie in diesem Beispiel *Payroll Samstag um 1 UHR plus täglich um 7 Uhr* als Backup-Zeitplan aus und klicken Sie dann auf *Weiter*.

+
In diesem Beispiel enthält der ausgewählte Zeitplan sowohl die wöchentlichen als auch die täglichen Zeitpläne, die Sie zuvor konfiguriert haben.

.. Geben Sie im Eigenschaftenblatt Backup Policy den Namen des Backup-Knotens und die Aufbewahrungszeiten für tägliche, wöchentliche oder monatliche Backups an.
+
Geben Sie in diesem Beispiel eine tägliche Backup-Aufbewahrung von 10 Tagen und eine wöchentliche Backup-Aufbewahrung von 52 Wochen an. Klicken Sie nach dem Ausfüllen jedes Eigenschaftenblatts auf *Weiter*.

+
Nachdem alle Eigenschaftenblätter abgeschlossen sind, zeigt der Assistent zum Hinzufügen von Schutzrichtlinien eine Zusammenfassung für die Schutzrichtlinie an, die Sie erstellen möchten.



. Klicken Sie auf *Fertig stellen*, um Ihre Änderungen zu speichern.


Die *TechCo Payroll Data: Backup* Protection Policy ist unter den anderen Richtlinien für Protection Manager aufgelistet.

Der DBA-Partner kann nun mit SnapManager für Oracle diese Richtlinie auflisten und zuweisen, wenn das Datenbankprofil für die zu sichernden Daten erstellt wird.
