---
permalink: unix-installation-7mode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark 
summary: Markeninformationen 
---
= Markeninformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp, das NetApp -Logo, Go Further, Faster, AltaVault, ASUP, AutoSupport, Campaign Express, Cloud ONTAP, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Fitness, Flash Accel, Flash Cache, Flash Pool, FlashRay, FlexCache, FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, GetSuccessful, LockVault, Manage ONTAP, Mars, MetroCluster, MultiStore, NetApp Insight, OnCommand, ONTAP, ONTAPI, RAID DP, RAID-TEC, SANtricity, SecureShare, Simplicity, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, SnapIntegrator, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator SnapVault, StorageGRID, Tech OnTap, Unbound Cloud, WAFL und andere Namen sind Marken oder eingetragene Marken von NetApp, Inc. in den Vereinigten Staaten und/oder anderen Ländern. Alle anderen Marken oder Produkte sind Warenzeichen oder eingetragene Warenzeichen ihrer jeweiligen Inhaber und sollten als solche behandelt werden.  Eine aktuelle Liste der NetApp -Marken ist im Internet verfügbar unter http://www.netapp.com/us/legal/netapptmlist.aspx[] Die
