---
permalink: unix-installation-7mode/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademark 
summary: Markeninformationen 
---
= Markeninformationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


NetApp, das NetApp Logo, Go further, faster, AltaVault, ASUP, AutoSupport, Campaign Express, Cloud ONTAP, Clustered Data ONTAP, Customer Fitness, Data ONTAP, DataMotion, Fitness, Flash Accel, Flash Cache, Flash Pool, FlashRay, FlexArray, FlexCache FlexClone, FlexPod, FlexScale, FlexShare, FlexVol, FPolicy, GetSuccessful, LockVault, Manage ONTAP, Mars, MetroCluster, MultiStore, NetApp Insight, OnCommand, ONTAP ONTAPI, RAID DP, RAID-TEC, SANtricity, SecureShare, Einfachheit, Simulate ONTAP, Snap Creator, SnapCenter, SnapCopy, SnapDrive, Integration, SnapLock, SnapManager, SnapMirror, SnapMover, SnapProtect, SnapRestore, Snapshot, SnapValidator, SnapVault, StorageGRID, Tech OnTap, Unbound Cloud, WAFL und andere Namen sind Marken oder eingetragene Marken von NetApp Inc. In den USA und/oder in anderen Ländern. Alle anderen Markennamen oder Produkte sind Marken oder eingetragene Marken der jeweiligen Rechtsinhaber und als solche anzuerkennen. Eine aktuelle Liste der NetApp Marken finden Sie im Internet unter http://www.netapp.com/us/legal/netapptmlist.aspx[].
