---
permalink: unix-installation-7mode/task_configuring_the_snapmanager_repository.html 
sidebar: sidebar 
keywords: configure, snapmanager, repository, database, instance, manage, user, interface, ui, command-line, interface, cli 
summary: Sie müssen das SnapManager-Repository in der Repository-Datenbankinstanz konfigurieren. Die Repository-Datenbank speichert Metadaten für Datenbanken, die von SnapManager gemanagt werden. 
---
= SnapManager-Repository wird konfiguriert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das SnapManager-Repository in der Repository-Datenbankinstanz konfigurieren. Die Repository-Datenbank speichert Metadaten für Datenbanken, die von SnapManager gemanagt werden.

* Sie müssen die Repository-Datenbankinstanz erstellt haben.
* Sie müssen den Oracle-Benutzer für die Repository-Datenbankinstanz mit den erforderlichen Berechtigungen erstellt haben.
* Sie müssen die Details der Repository-Datenbankinstanz in die Datei nsnames.ora enthalten haben.


Sie können das SnapManager-Repository entweder über die SnapManager-Benutzeroberfläche (UI) oder über die Befehlszeilenschnittstelle (CLI) konfigurieren. Mit diesen Schritten wird das Erstellen eines Repositorys mithilfe der SnapManager-Benutzeroberfläche erläutert. Sie können auch die CLI verwenden, wenn Sie es bevorzugen.

Informationen zum Erstellen des Repositorys mithilfe von CLI finden Sie im _SnapManager for Oracle Administration Guide for UNIX_.

. Klicken Sie im linken Bereich der SnapManager-Benutzeroberfläche mit der rechten Maustaste auf *Repositories*.
. Wählen Sie *Neues Repository erstellen* und klicken Sie auf *Weiter*.
. Geben Sie im Fenster Repository-Datenbankkonfigurationsinformationen die folgenden Informationen ein:
+
|===
| In diesem Feld... | Tun Sie das... 


 a| 
*Benutzername*
 a| 
Geben Sie den Namen des Benutzers ein, den Sie für die Repository-Datenbankinstanz erstellt haben.



 a| 
*Passwort*
 a| 
Geben Sie das Passwort ein.



 a| 
*Gastgeber*
 a| 
Geben Sie die IP-Adresse des Hosts ein, auf dem die Repository-Datenbankinstanz erstellt wird.



 a| 
*Port*
 a| 
Geben Sie den Port ein, der für die Verbindung zur Repository-Datenbankinstanz verwendet wird. Der Standardport ist 1521.



 a| 
*Dienstname*
 a| 
Geben Sie den Namen ein, den SnapManager für die Verbindung zur Repository-Datenbankinstanz verwendet. Je nach den Details in der Datei nsnames.ora kann es sich um den kurzen Servicenamen oder den vollqualifizierten Servicenamen handelt.

+

|===
. Überprüfen Sie im Fenster Projektarchiv hinzufügen die Konfigurationszusammenfassung und klicken Sie auf *Hinzufügen*.
+
Wenn der Vorgang fehlschlägt, klicken Sie auf die Registerkarte *Operationsinformationen*, um anzuzeigen, was den Vorgang zum Scheitern verurteilt hat. Die Fehlerdetails werden auch im Betriebsprotokoll unter /var/log/smo erfasst.

. Klicken Sie Auf *Fertig Stellen*.
+
Das Repository wird im linken Fensterbereich unter dem Baum *Repositories* aufgelistet. Wenn das Repository nicht angezeigt wird, klicken Sie mit der rechten Maustaste auf *Repositories* und klicken Sie auf *Aktualisieren*.



*Verwandte Informationen*

https://library.netapp.com/ecm/ecm_download_file/ECMP12471546["SnapManager 3.4 für Oracle – Administratorhandbuch für UNIX"]
