---
permalink: unix-installation-7mode/task_verifying_the_oracle_listener_configuration.html 
sidebar: sidebar 
keywords: listener, process, client, connection, request, receive, traffic, status 
summary: Der Listener ist ein Prozess, der Client-Verbindungsanforderungen abhört. Es empfängt eingehende Client-Verbindungsanfragen und verwaltet den Datenverkehr dieser Anfragen an die Datenbank. Bevor Sie eine Verbindung zu einer Zieldatenbank oder einer Repository-Datenbankinstanz herstellen, können Sie mit dem STATUS-Befehl die Listener-Konfiguration überprüfen. 
---
= Überprüfen der Oracle Listener-Konfiguration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Der Listener ist ein Prozess, der Client-Verbindungsanforderungen abhört. Es empfängt eingehende Client-Verbindungsanfragen und verwaltet den Datenverkehr dieser Anfragen an die Datenbank. Bevor Sie eine Verbindung zu einer Zieldatenbank oder einer Repository-Datenbankinstanz herstellen, können Sie mit dem STATUS-Befehl die Listener-Konfiguration überprüfen.

Der STATUS-Befehl zeigt grundlegende Statusinformationen zu einem bestimmten Listener an, einschließlich einer Zusammenfassung der Listener-Konfigurationseinstellungen, Listener-Protokolladressen und einer Zusammenfassung der bei diesem Listener registrierten Dienste.

. Geben Sie an der Eingabeaufforderung den folgenden Befehl ein: 'Lsnrctl STATUS'
+
Der dem Listener-Port zugewiesene Standardwert ist 1521.


